### ISSUE TITLE
Grid page numbers display in block instead of inline

### ISSUE THREAD

**Issue by TheoGit** [telerik/kendo-angular2#103]
The  css for the grid page numbering (.k-page-numbers) is set to block instead of inline - so the page numbers are displaying vertically

**Comment by inikolova** [comment]
I checked Kendo UI Grid for Angular 2 demos and **.k-grid .k-pager-numbers** element has **_display: inline-block_** set. Could you please provide a plunker which demonstrates the issue?

**Comment by TheoGit** [comment]
Currently I'm using my company's API do get secure data; will take me a while to set up a Plunker - I will continue to try to get it to work as is and set up a Plunker demo if I can't - thanks for your response

**Comment by TheoGit** [comment]
I figured out the issue; originally I did [pageable] = "true";  I found a code example on your website that does  [pageable]="{
            buttonCount: buttonCount,
            info: info,
            type: type,
            pageSizes: pageSizes,
            previousNext: previousNext
          }"
and it works fine now.   Thanks for responding to my issue so quickly; this is definitely closed.

**Comment by TheoGit** [comment]
Update: It actually doesn't work;  I copied the code directly from you're example (http://www.telerik.com/kendo-angular-ui/components/grid/#installation)
That works fine in Plunker and but it doesn't work in my enviroment.

Here's the difference - on you example page if I inspect the <ul> of page numbers of the grid the css has a line thru display and line-style-type because it's using the .k-grid .k-pager-numbers:
ul, menu, dir {
    display: block;
    list-style-type: disc;
    ....

however for some reason on my page when I inspect the <ul> of the page numbers the css DOES NOT have a line thru display and line-style-type; so it's ignoring the k-grid .k-pager-numbers

lastly, I'm using the grid on existing html page, I did't use the 'template' - could that make a difference?

**Comment by TheoGit** [comment]
LAST UPDATE, if I point to you're css from the Telerik website it works 
http://www.telerik.com/kendo-angular-ui/npm/node_modules//@telerik/kendo-theme-default/dist/all.css

I downloaded the Telerik kendo-theme-default and I'm pointing the version on my machine and that's not working; I will update the Telerik kendo-them-default with a new update and see if that works

**Comment by KirilNN** [comment]
You can see the code for the kendo-theme-default [here](https://github.com/telerik/kendo-theme-default/blob/42839c13d62297e1173a9ff1075f3216fd8a9a4a/styles/grid/_layout.scss#L163). The following CSS rule:

     .k-grid .k-pager-numbers:
        ul, menu, dir {
        display: block;
        list-style-type: disc;

is nowhere to be found.

**Comment by TheoGit** [comment]
Resolved!  The issue was the Telerik .css needed to be referenced in the angular-cli.json
