### ISSUE TITLE
Grid DetailRow only if property exists

### ISSUE THREAD

**Issue by jvanderbiest** [telerik/kendo-angular2#106]
I would like to only show a detail template if a specific property (Category) exists. Currently it renders an expand icon if there is no detail template content. The problem is that I cannot use an *ngIf directive on the template element itself as I don't have access to the property.

Plunker: http://plnkr.co/edit/CKERCaoU4PEAi7Qya9VT?p=preview

Original stackoverflow question: http://stackoverflow.com/questions/40883426/grid-detailrow-only-if-property-exists/

**Comment by rusev** [comment]
We can introduce `condition` to the `kendoDetailTemplate` directive where based on `dataItem` and `rowIndex` (master row index) you can build your conditional logic. Here is how detail template definition might look in the consumer component:

         <div *kendoDetailTemplate="let dataItem, let rowIndex = rowIndex; condition: myCondition">
            <category-details [category]="dataItem"></category-details>
        </div>

with `<template>` element:

        <template kendoDetailTemplate let-dataItem let-rowIndex="rowIndex"
          [kendoDetailTemplateCondition]="myCondition">
            <category-details [category]="dataItem"></category-details>
        </template>

and here is how `myCondition` function looks like:

      myFn(dataItem: any, rowIndex: number) { return dataItem.CategoryID % 2 == 0; }

However there is an open question - what do you expect to see in the expand/collapse column when there isn't detail template for that master row?

Here is a how all this might look with expand/collapse icon removed if `myCondition` function returns `false`:
![conditionaldetailtemplate](https://cloud.githubusercontent.com/assets/961035/20786678/1993f490-b7b0-11e6-99de-7cc7c475299e.png)

**Comment by jvanderbiest** [comment]
@rusev If there isn't a detail row, there should be no expand icon (as this is now the case...). Looks good in your screenshot and +1 for the condition approach!

**Comment by rusev** [comment]
@jvanderbiest I'm logging this for implementation. We will update this issue once the Grid package is released with this functionality.

**Comment by bhoopaljanga** [comment]
can we show/hide this based on input, we want to enable with a flag across the app
