### ISSUE TITLE
Changing DropDown width using bootstrap.

### ISSUE THREAD

**Issue by dzmitrypaulouski** [telerik/kendo-angular2#108]
Hi.

Is it possible to change DropDown width using Bootstrap Grid System?

I am try to use it this way:
```
            <div class="col-md-9">
                <kendo-dropdownlist [data]="data"
                                    [textField]="'textField'"
                                    [valueField]="'valueField'">
                </kendo-dropdownlist>
            </div>
```

In this case I have default width.
I tried to set "width:100%" but in this case I have such issue:

![image](https://cloud.githubusercontent.com/assets/10211927/20796043/580cf19c-b7e5-11e6-9249-b1aad6f0a736.png)

**Comment by rusev** [comment]
Could you please elaborate on the problem? A runnable example of the issue will help a lot.

Thank you in advance.

**Comment by dzmitrypaulouski** [comment]
Sorry I've just missclicked

**Comment by inikolova** [comment]
Hi, There is a default **width 12.4 em** which is set to the dropdownlist. To achieve the expected result you should override it. Take a look at this example: [http://plnkr.co/edit/?p=preview]

Keep in mind that Bootstrap requires its grid classes to be placed within a **.row** element, which on the other hand must be placed within a **.container** or **.container-fluid** class: [http://getbootstrap.com/css/#grid](url)

**Comment by dzmitrypaulouski** [comment]
@inikolova Thanks you a lot! Solution with .k-dropdown class width 100% works good.
