### ISSUE TITLE
panel bar cant select child item by default

### ISSUE THREAD

**Issue by BtShp** [telerik/kendo-angular2#109]
Hi,
I have panel bar with child items, using it for routing. the parent cant be selected.
I cant select element by default- selected="true" dosnt work for me
also i need a way to set item open by default

**Comment by KirilNN** [comment]
Can you share a plunkr with us, or some runnable code that we can look at? I am not sure I am able to reproduce the issue locally.

Thanks!

**Comment by rkonstantinov** [comment]
We are closing this issue for now.  @BtShp feel free to reopen it with the requested additional information.
