### ISSUE TITLE
dialog component of kendo-angular2 not working with angular cli to 2.2.1

### ISSUE THREAD

**Issue by AlfredMan** [telerik/kendo-angular2#110]
When I updated my angular cli to 2.2.1, it seems the dialog component of kendo-angular2 is not working anymore:
on ng serve running any example from  here:
[](http://www.telerik.com/kendo-angular-ui/components/dialog/)

the console will report these :

ERROR in ./~/@progress/kendo-angular-dialog/dist/es/dialog.component.js
Module not found: Error: Can't resolve '@telerik/kendo-theme-default/styles/packages/dialog' in '/Applications/XAMPP/xamppfiles/htdocs/cli/kendo/node_modules/@progress/kendo-angular-dialog/dist/es'
 @ ./~/@progress/kendo-angular-dialog/dist/es/dialog.component.js 3:0-61
 @ ./~/@progress/kendo-angular-dialog/dist/es/main.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

Is there any other dependencies I should install now?  Please help

**Comment by tsvetomir** [comment]
Thanks for the heads-up, should be fixed in 0.13.1

**Comment by AlfredMan** [comment]
Thats fast!!!! Thanks a tons!
