### ISSUE TITLE
Question: Dialog Box

### ISSUE THREAD

**Issue by squadwuschel** [telerik/kendo-angular2#111]
Hi,

in my current Angular 1 apps I am using the Modal component very often implemented by Ui-Bootstrap

https://angular-ui.github.io/bootstrap/#/modal

Is the Dialog the pendant for this control in kendo Ui ng2?

**Comment by KirilNN** [comment]
The Kendo UI  Dialog is the alternative of the Modal component in Ui-Bootstrap. Check it out:

http://www.telerik.com/kendo-angular-ui/components/dialog/

**Comment by squadwuschel** [comment]
Will there beo some more Improvemts to the Kendo UI Dialog like the option to set the size (width) of the dialog or like the ui bootstrap implementation for modal 

https://ng-bootstrap.github.io/#/components/modal

to be able to create the dialog more globally to call it anywhere and you only have to insert one component in your main app for multiple different modals?

**Comment by KirilNN** [comment]
For the width and height option - currently they cannot be set from the outside, so I have filed [this](https://github.com/telerik/kendo-angular2/issues/113) issue.

Regarding the second question - we have logged this [issue](https://github.com/telerik/kendo-angular2/issues/112)
