### ISSUE TITLE
Button - active even tough togglable is set to false

### ISSUE THREAD

**Issue by P-H-F** [telerik/kendo-angular2#114]
When using a non-toggleable button `[togglable]=false]` the button keeps its active state `.k-state-active` until the next click.

From my point of view that would be the functionality of a toggleable button.

Originally I expected the button the remove the active state when the 'click event has ended'. Right now both versions look identical to me.

### Plunker:
http://plnkr.co/edit/knPFWqrHhIdwmfnTWdW1?p=preview

**Comment by KirilNN** [comment]
Maybe we should add k-state-pressed class that is toggled on mousedown/up for `[togglable]=false]` buttons.
