### ISSUE TITLE
Dropdownlist in dialog displays options outside the bounds of the dialog

### ISSUE THREAD

**Issue by sgantrim** [telerik/kendo-angular2#116]
http://plnkr.co/edit/ODUL0etepbXksEtePmEN?p=preview

![ddl](https://cloud.githubusercontent.com/assets/11021014/20840911/7b872060-b877-11e6-9fac-a8f8507333c1.png)

**Comment by KirilNN** [comment]
It think that this issues is related to - https://github.com/telerik/kendo-angular2/issues/115

**Comment by ggkrustev** [comment]
Indeed this is a duplicate to #115
