### ISSUE TITLE
Kendo Button , can it has an option to be rendered stateless? (Picture attached to explain)

### ISSUE THREAD

**Issue by AlfredMan** [telerik/kendo-angular2#117]
At the moment, when a button is clicked, it got rendered differently as if it shows on off stage , which is good for some cases

In the attached jpg, it shows the button has shadow after one click and then with no shadow after next click

Can an option be added to make the button stateless? 

![kendobutton](https://cloud.githubusercontent.com/assets/9289253/20864989/8b6d6d18-b9fd-11e6-82a5-1217439b7067.jpg)

**Comment by KirilNN** [comment]
This is related to - https://github.com/telerik/kendo-angular2/issues/114

As soon as that is implemented, it will fix this issue as well.

**Comment by AlfredMan** [comment]
Thx for letting me know. I guess we just have to wait

**Comment by KirilNN** [comment]
I will close this issue, and leave the other one open.
