### ISSUE TITLE
hyphen is a valid email address character

### ISSUE THREAD

**Issue by DaveMBush** [telerik/kendo-angular2#121]
Can't find any better place to report this so here you go...

I tried to register on the telerik site and got stopped entering my email address which has a hypen in it.  In fact all of the contractors that work here end with -ND@company.com

**Comment by tsvetomir** [comment]
Thanks for reporting this problem and apologies for the caused inconvenience.
We'll forward it to someone who can amend the form validation rules.

/cc @petyosi

**Comment by DaveMBush** [comment]
Looks like it has been fixed
