### ISSUE TITLE
[defaultItem] being listed twice in Dropdown List Component, clicking 1st will crash UI

### ISSUE THREAD

**Issue by AlfredMan** [telerik/kendo-angular2#122]
Dropdown List of "Object types" 
will list 2x default item if [defaultItem] is inputted

If user click on the 1st duplicated default item, will crash the UI

In the attached jpg, you can see "No Color coding" is listed twich, which is not right.

        <kendo-dropdownlist
        [data]="primaryCCCategories"
        
        [textField]="'display_name'"
        [valueField]="'index'"
        [value]="primaryCCCategories[_ccService.selectedPrimaryCCIndex]"
        [defaultItem]="primaryCCCategories[0]"
        (selectionChange)="onPrimaryCCSelect($event)"
         >
        </kendo-dropdownlist>

This is the sample usage to have this bug repeated. 

The data itself is just an array of object. All fields listed in the component is provided in the object to the component.

<img width="183" alt="screen shot 2016-12-06 at 19 11 08" src="https://cloud.githubusercontent.com/assets/9289253/20939718/c591bddc-bbe7-11e6-83b7-2ff4cd7d2f6e.png">

**Comment by KirilNN** [comment]
I think that the duplication of the item is expected. However I was not able to reproduce the UI crash. Can you check this [plunkr](http://plnkr.co/edit/tAz7Sez1GcKuiz8Xs2gu?p=preview) and let me know what I missed?

**Comment by AlfredMan** [comment]
I think the “bug" happens when you try to hook (selectionChange)=“onSelectionChange($event)”

Selecting the first duplicated item will also trigger seletionChange and the $event will be null. Of course we can write some guard on every kendo dropdownlist component to watch this. But I don’t understand why the ‘dummy duplicated item’ is selectable and why will it trigger (selectionChange).

Thanks

Alfred

**Comment by valchev** [comment]
@AlfredMan the default item cannot be part of the data collection. If you have an item in the data collection that should be pre-selected when the component is initialised, use the `value` property.

For example:

`public data: number[] = ["select", "foo", "bar", "baz"];`
`<kendo-dropdownlist [data]="data" value="'select'"></kendo-dropdownlist>`

The `defaultItem` property aims to provide the developer with ability to define a dummy item that will be used when the end user does not want to select value from the data or when the end user wants to clear the selection.

The `selectionChange` event will emit each time the selection changes and should provide the selected value as argument to the event handler. Currently when the `defaultItem` is selected via mouse (or enter key) the argument is `undefined` (works fine when selection is changed via keyboard arrows). [example](http://plnkr.co/edit/tAz7Sez1GcKuiz8Xs2gu?p=preview)

I can confirm that this is a bug. Thank you for bringing it to our attention, I will provide a fix in a short period of time.
