### ISSUE TITLE
kendo-angular-upload not working?

### ISSUE THREAD

**Issue by AlfredMan** [telerik/kendo-angular2#123]
After I installed Kendo's upload into my module
import { UploadModule } from '@progress/kendo-angular-upload';

  imports: [
...
    UploadModule,
]

And used it in the component as advised:
    <kendo-upload
    [saveUrl]="uploadSaveUrl"
    [removeUrl]="uploadRemoveUrl"
    [disabled]="true"
  ></kendo-upload>

The compiler (I am using angular cli) reports these here... Is there anything I can do to stop this and start using Kendo's upload for angular2?

Thanks

 /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/file-list-item-action-button.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/file-list-multiple-items.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/file-list.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/upload-events.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/upload-status-total.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/upload.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] Checking finished with 6 errors
[default] Checking started in a separate process...
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/file-list-item-action-button.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/file-list-multiple-items.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/file-list.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/upload-events.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/upload-status-total.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] /Applications/XAMPP/xamppfiles/htdocs/cli/ops/node_modules/@progress/kendo-angular-upload/dist/npm/js/upload.component.d.ts:1:1 
    Cannot find type definition file for 'chai'.
[default] Checking finished with 6 errors

**Comment by tsvetomir** [comment]
Thanks for the heads-up. We've removed the erroneous reference.

Please update to version 0.11.1 or later.

**Comment by AlfredMan** [comment]
Perfect!!!! Works as advertised again!!!
