### ISSUE TITLE
Dialog-Action-Button [disabled] styling

### ISSUE THREAD

**Issue by P-H-F** [telerik/kendo-angular2#124]
When disabling a `kendo-button` within the `kendo-dialog-actions` a gray bar is shown on the bottom of the button.

_I was not sure if that belongs here or to the [kendo-theme-default](https://github.com/telerik/kendo-theme-default) repository. If it doesn't belong here, let me know and I'll create a new issue over there._ 

### Plunker:
http://plnkr.co/edit/5mgIKaUWh7z6o6xGTjPD?p=preview

**Comment by gyoshev** [comment]
Thanks for the feedback! It is a valid bug in the theme. Since the bug will also be relevant for the jQuery widgets (once the theme supports them), I've [moved it to the theme repo](https://github.com/telerik/kendo-theme-default/issues/50).
