### ISSUE TITLE
Simple examples for toODataString method

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular2#125]
Can you provide us with some simple toODataString examples? ( kendo-data-query)
I tried it like this: 
 `toODataString({
           filter: {
              logic: "or",
                filters: [
                    { field: "discontinued", operator: "eq", value: true },
                    { field: "unitPrice", operator: "lt", value: 22 }
                ]
            }
})` 

but all i get is an empty string.

**Comment by rkonstantinov** [comment]
I'm afraid that the toODataString function currently supports only sorting and paging. We will add filtering in the feature.
