### ISSUE TITLE
Grid Pagination List links.

### ISSUE THREAD

**Issue by dzmitrypaulouski** [telerik/kendo-angular2#126]
Hello,

I am using Grid component and found that pagination buttons are <a> tags with href="#".
It is a problem for me because I am implementing SPA using Page Router Outlet. So when I click on some page it's performs a redirection to mywebsite.com/#.

Are there any workaround to use it with ui routing?

As a pagination example I've used this plunker: http://plnkr.co/edit/EdI5Mh7NF3mE49pZv1N1?p=preview

**Comment by KirilNN** [comment]
@dzmitrypaulouski you haven't saved the plunkr and therefore its empty. Can you update it?

**Comment by dzmitrypaulouski** [comment]
@KirilNN http://plnkr.co/edit/EdI5Mh7NF3mE49pZv1N1?p=preview

**Comment by KirilNN** [comment]
It looks fine to me? How do I reproduce the issue?

**Comment by dzmitrypaulouski** [comment]
@KirilNN I just have an application that uses Angular 2 page-router-outler with HTML 5 Base Href strategy.
In this case when I click on some page (e.g. 5) the navigation performs because pagination uses the Hash location strategy (href="#").

The main question is grid supports the <base href="/"> strategy?

**Comment by KirilNN** [comment]
Here is an example that uses the `<base href="/">` strategy - https://plnkr.co/edit/gpkQP3c3iwBHJv577gwX?p=preview

In this case there is a navigation item in the `app.component.ts` file that looks like this:

`<a href="#" (click)="click($event)">Foo</a>`

In the attached handler we have:

    click(e) {
        console.log(1);
        return false;
    }

When you have `return false` - the default action will be prevented, and the page **won't** be reloaded - this is exactly the same code that we use in the Pager. Removing the return statement, will cause the page to reload on click of the anchor - you can reproduce it in the plunkr.

I can see that you closed the issue - did you manage to resolve it? What was the cause for it?
