### ISSUE TITLE
Panel Bar: Keyboard Navigation. Option to turn off? Can't have input box inside panel bar with user typing "space"

### ISSUE THREAD

**Issue by AlfredMan** [telerik/kendo-angular2#127]
Is there anyway to turn off Keyboard navigation for the NG2 Panel Bar?
Eg, if we have an input box inside the kendo-panelbar, user can't type "space" in the input caused it will collapse the kendo-panelbar, which is quite annoying.

For now, I have to do (keydown)="$event.stopPropagation()" in every input inside the new kendo-panelbar to work around this.

`<kendo-panelbar >
    <kendo-panelbar-item title="Background Setting" expanded="true" focused="true">
      <template kendoPanelBarContent>
            <input (keydown)="$event.stopPropagation()">
      </template>
    </kendo-panelbar-item>
</kendo-panelbar>`

**Comment by rusev** [comment]
Hello Alfred,

Indeed this is another bug. Thank you for taking the time to report this problem.

**Comment by Dimitar-Goshev** [comment]
Hello Alfred,
We have just fixed this issue.
