### ISSUE TITLE
Kendo TabStrip: Can (select) emit event on tab which is set to [disabled]="true"

### ISSUE THREAD

**Issue by AlfredMan** [telerik/kendo-angular2#128]
Is it possible for  (select) event emitter to emit an event even if the tab title is set to [disabled]="true"

The use case is: 

If we have eg 2 tabs. Each tab has a form with different input. 
If a user haven't saved the data in a tab, he shouldn't be allowed to navigate to another tab.

The kendo tab strip can't do this yet. We can eg .link the [disabled]="formDirty" . However, when user try to click on the tab, he wouldn't be informed why he can't goto the tab. Caused Kendo's UI just disabled it and I can't even get any event when user click on the tab and we ask user to either save or cancel the change before he can navigate to other tab.

So if the (select) event emitter can emit the disabled tab being selected  (and of course don't jump to the tab caused its disabled) This should resolve the problem.  (Or if the inividual tab can have event emitter when being clicked, disabled or not, that may also work)

Hope I am not asking too much.

Thanks
Alfred

**Comment by rusev** [comment]
Hello Alfred,

`select` event should trigger only when the user navigates to another tab. 

However you can use `kendoTabTitle` directive and attach `click` handler to it. It will execute regardless of whether the tab is disabled or not. 

Example - http://plnkr.co/edit/BUnx1ohqbaaFzttqVHZu?p=preview

**Comment by AlfredMan** [comment]
<template kendoTabTitle>
              <span (click)="titleClick()">
                some title
              </span>
            </template>

The code above should solve the scenario described in this issue. User should know there is a template for title as well as content.  (not in the overview page  at the moment) ^^

Seems the code in Kendo's c TabStrip omponent API page for TabTitleDirective is not working
http://www.telerik.com/kendo-angular-ui/components/layout/api/TabTitleDirective/

**Comment by rusev** [comment]
The layout package documentation will be revised.

Regarding the broken example - the fix for it will be available with the next update of the documentation site. Thank you for reporting it.
