### ISSUE TITLE
how to define peerDependencies for grid - any code demo ?

### ISSUE THREAD

**Issue by yaronmil** [telerik/kendo-angular2#129]
i got this error :
ERROR in ./~/@progress/kendo-angular-grid/dist/es/field-accessor.pipe.js
Module not found: Error: Can't resolve '@progress/kendo-data-query' in 'D:\...\node_modules\@progress\kendo-angular-grid\di
st\es'
 @ ./~/@progress/kendo-angular-grid/dist/es/field-accessor.pipe.js 2:0-52
 @ ./~/@progress/kendo-angular-grid/dist/es/shared.module.js
 @ ./~/@progress/kendo-angular-grid/dist/es/main.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in [default] D:\Amitim\node_modules\@progress\kendo-angular-grid\dist\es\change-event-args.interface.d.ts:1:31 
Cannot find module '@progress/kendo-data-query'.

**Comment by rkonstantinov** [comment]
Peer dependencies are installed the same way as any other dependencies. In the case in question 
```
npm install --save @progress/kendo-data-query
```
Installation instructions for data-query package can be found [here](http://www.telerik.com/kendo-angular-ui/components/dataquery).

**Comment by yaronmil** [comment]
running this line 

`npm install --save @progress/kendo-data-query`

results this errors 

```
+-- UNMET PEER DEPENDENCY @angular/compiler@2.3.0
+-- UNMET PEER DEPENDENCY @angular/core@2.3.0
+-- @progress/kendo-data-query@0.3.1
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-rc.5
`-- UNMET PEER DEPENDENCY zone.js@0.6.26
```

trying to :

`npm i  @angular/compiler@2.3.0`

which results the same erros :

```
+-- UNMET PEER DEPENDENCY @angular/compiler@2.3.0
+-- UNMET PEER DEPENDENCY @angular/core@2.3.0
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-rc.5
`-- UNMET PEER DEPENDENCY zone.js@0.6.26
```

packages.json :

```
"dependencies": {
    "@angular/common": "^2.1.2",
    "@angular/compiler": "^2.1.2",
    "@angular/core": "^2.1.2",
    "@angular/forms": "^2.1.2",
    "@angular/http": "^2.1.2",
    "@angular/material": "^2.0.0-alpha.10",
    "@angular/platform-browser": "^2.1.2",
    "@angular/platform-browser-dynamic": "^2.1.2",
    "@angular/router": "^3.1.2",
    "@progress/kendo-data-query": "^0.3.1",
    "@types/hammerjs": "^2.0.33",
    "core-js": "^2.4.1",
    "rxjs": "^5.0.0-rc.2",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.6.26"
  },
```

what am i doing wrong here ??

**Comment by rkonstantinov** [comment]
Could you please delete `node_modules` folder and execute `npm install`.
