### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular2#13]
## Background
The [@telerik/kendo-intl](https://github.com/telerik/kendo-intl) package provides the basic support for internationalization functions - parsing, formatting and calendars.

The locale data comes from the [cldr-data](https://www.npmjs.com/package/cldr-data) package. Kudos to @ggkrustev and @danielkaradachki for taming this monster data set.

## Goals

* Built-in i18n that *just works* for the default en-US locale
* Loading additional locales should be easy
* Custom implementations should be easy to plug-in

## Implementation

We start by defining an abstract class *IntlService* class that defines our service interface. We're not using a TypeScript interface as the Angular DI requires a concrete type.

```ts
import { DateFormatOptions, DateFormatNameOptions, NumberFormatOptions }
  from '@telerik/kendo-intl';

export abstract class IntlService {
  public abstract format(format: string, ...values: any[]): string;

  public abstract toString(value: string, format: string): string;

  public abstract formatDate(
    value: Date,
    format: String | DateFormatOptions
  ): string;

  public abstract parseDate(
    value: string,
    format?: string | DateFormatOptions | string[] | DateFormatOptions[]
  ): Date;

  public abstract parseNumber(
    value: string,
    format?: string | NumberFormatOptions
  ): number;

  public abstract formatNumber(
    value: number,
    format: string | NumberFormatOptions
  ): string;

  public abstract dateFormatNames(options: DateFormatNameOptions): any;

  public abstract firstDay(): number;
}
```

This class is inherited and fully implemented by the *CldrIntlService* default implementation.
Both classes will be made available as part of the *@progress/kendo-angular-intl* package.

### Scenario: Load data for additional locales

* Install [cldr-data](https://www.npmjs.com/package/cldr-data)

  `npm install --save cldr-data`

* For Webpack, configure [json-loader](https://www.npmjs.com/package/json-loader). See [loaders](https://webpack.github.io/docs/loaders.html).

  `npm install --save json-loader`

* Load the desired locales

```ts
import { NgModule, LOCALE_ID } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';

import { load } from '@telerik/kendo-intl';
load(
  require(`json!cldr-data/main/bg/numbers.json`),
  require(`json!cldr-data/main/bg/currencies.json`),
  require(`json!cldr-data/main/bg/ca-gregorian.json`),
  require(`json!cldr-data/main/bg/timeZoneNames.json`)
);

@NgModule({
    bootstrap:    [AppComponent],
    declarations: [AppComponent],
    imports:      [BrowserModule],
    providers:    [{ provide: LOCALE_ID, useValue: 'bg-BG' }]
})
export class AppModule {
}
```

### Scenario: Custom localization service

* Inherit *IntlService* or *CldrService* and implement/override its memebers

```ts
import { IntlService } from '@progress/kendo-angular-intl';

@NgModule({
    bootstrap:    [AppComponent],
    declarations: [AppComponent],
    imports:      [BrowserModule],
    providers: [{
      provide: IntlService,
      useClass: MyIntlService
    }]
})
export class AppModule {
}
```

### Scenario: Use localization service in a component

* Add *CldrService* as a provider to your module
* Inject it in your component
* Optionally, load CLDR data for the desired locales. By default only en-US will work.

```ts
import { CldrService } from '@progress/kendo-angular-intl';

@NgModule({
    bootstrap:    [AppComponent],
    declarations: [AppComponent],
    imports:      [BrowserModule],
    providers: [CldrService]
})
export class AppModule {
}
```

```ts
import { CldrService } from '@progress/kendo-angular-intl';

@Component({
  providers: [CldrService],
  selector: 'my-component',
  template: `
    {{ intl.formatNumber(42, "c") }}
  `
})
export class MyComponent {
  constructor(public intl: CldrIntlService) {
  }
}
```
## Questions

* How do we handle missing locale information. Do we throw an error or use the default locale?

/cc @underlog @rkonstantinov @danielkaradachki @rusev @KirilNN

**Comment by underlog** [comment]
What may cause the missing locale? If it is a developer mistake, then let's throw an error.

**Comment by tsvetomir** [comment]
The scenario is rather trivial:
* The developer specifies a locale, say *fi* for his Angular application
* She *does not* load the *cldr-data/main/fi/...*
* Any Kendo widgets that depends on internationalization will now throw a `Missing locale info for: fi` error.

**Comment by underlog** [comment]
👍 Sounds like something that should throw an error.

**Comment by tsvetomir** [comment]
Okay, that's what we do now. I'll just try to make it more descriptive and add a link to the docs when we have them.

**Comment by tsvetomir** [comment]
Update: more application scenarios

**Comment by rkonstantinov** [comment]
As a side note. How do we feel about exposing a pipe to simplify the template usage?

**Comment by tsvetomir** [comment]
I don't see why not.  We can have two pipes - `date` and `number`.

We'll have to export an additional `IntlModule`, but it will keep the implementation details hidden.
Not sure how this will play with the built-in pipes though. We might need to prefix them.

**Comment by rusev** [comment]
We will need to prefix them otherwise they will collide with `CommonModule` pipes.

**Comment by tsvetomir** [comment]
Closing this for now as basic support is in. Pipes will be implemented in a separate update.
