### ISSUE TITLE
double clicking a form group inside a tabstrip will trigger unexpected (select) event from kendo's tabstrip:

### ISSUE THREAD

**Issue by AlfredMan** [telerik/kendo-angular2#130]
double clicking a form group inside a tabstrip will trigger unexpected (select) event from kendo's tabstrip:

eg, the following html template , if you double click inside the input element, 
it will trigger Kendo's (select)="selectNewTab($event). 

I believe this is a bug
```
<kendo-tabstrip (select)="selectNewTab($event)">
   <kendo-tabstrip-tab [title]="'General'"  [selected]="true">
        <template kendoTabContent>
    

 <form (ngSubmit)="onSubmit()" #generalForm="ngForm" class="setting-container">
      <div class="form-group setting-row">
        <label class="setting-row-key" for="name">Name:</label>
        <input class="setting-row-value" type="text" class="form-control" id="name"
               required
               [(ngModel)]="whatever" name="name"
               #name="ngModel" >
      </div>
    </form>

 
        </template>
   </kendo-tabstrip-tab>
```

Thanks
Alfred

**Comment by rusev** [comment]
Hello Alfred,

I can confirm this is a bug. It is caused due to colliding [DOM select](https://developer.mozilla.org/en-US/docs/Web/Events/select) and component events. We will have to rename component event in order to prevent the collision.
