### ISSUE TITLE
sass issue

### ISSUE THREAD

**Issue by mhmo91** [telerik/kendo-angular2#132]
Hello, i'm using angular-cli, all is going great, except when i tried to include the telerik theme, 
I'm stuck with this error, Thankss!
ERROR in ./~/css-loader?sourcemap!./~/postcss-loader!./~/sass-loader?sourcemap!./src/styles.scss
Module build failed:
undefined
                       ^
      Argument `$color` of `lighten($color, $amount)` must be a color

Backtrace:
        node_modules/@telerik/kendo-theme-default/styles/base/_states.scss:5, in function `lighten`
        node_modules/@telerik/kendo-theme-default/styles/base/_states.scss:5
      in C:\Users\engmh\Desktop\eyekatcher\node_modules\@telerik\kendo-theme-default\styles\base\_states.scss (line 5, column 25)
 @ ./src/styles.scss 4:14-179
 @ multi styles

**Comment by gyoshev** [comment]
@mhmo91 it seems that some of the theme variables are not defined. The [line in question](https://github.com/telerik/kendo-theme-default/blob/master/styles/base/_states.scss#L5) refers to the $accent color, is that defined before including this file?

If that does not help, can you post some relevant (scss) code that shows how to reproduce the problem?

**Comment by mhmo91** [comment]
@gyoshev  that's your code man, not mine
This error is because i included your default theme sass file,  i followed those instructions
http://www.telerik.com/kendo-angular-ui/getting-started/#toc-adding-the-styles

**Comment by gyoshev** [comment]
@mhmo91 I tried reproducing the problem in https://github.com/gyoshev/kendo-angular2-startup, to no avail -- can you clone and run it? Also, which version of ng-cli are you using?

**Comment by mhmo91** [comment]
That's my npm file...

{
  "name": "***",
  "version": "0.0.0",
  "license": "propietary",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/material": "^2.0.0-alpha.10",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/router": "3.2.1",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.14",
    "@progress/kendo-angular-upload": "^0.11.1",
    "@telerik/kendo-theme-bootstrap": "^0.10.0",
    "@telerik/kendo-theme-default": "^1.32.1",
    "@types/firebase": "^2.4.30",
    "angular2-google-maps": "^0.16.0",
    "angularfire2": "^2.0.0-beta.6",
    "core-js": "^2.4.1",
    "firebase": "^3.6.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "ng2-material-select": "^0.1.4",
    "ng2-tag-input": "^0.4.4",
    "ng2-toastr": "^1.3.2",
    "ng2-validation": "^3.0.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.2.1",
    "@types/hammerjs": "^2.0.33",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "^1.0.0-beta.21",
    "codelyzer": "~1.0.0-beta.3",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "~2.0.3",
    "webdriver-manager": "10.2.5"
  }
}
=======================================================
my angular CLI file
{
  "project": {
    "version": "1.0.0-beta.21",
    "name": "****"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets/img",
        "assets/css/preloader.css"
      ],
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.scss"
      ],
      "scripts": [
      ],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "addons": [
  ],
  "packages": [
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}
------------------------------
i'll clone yours n run it later, updating angular-cli at the moment causes issues, i believe the problem could be a conflict with bootstrap sass or material2 or anythird party... in all cases i will get back to u when i can...

**Comment by gyoshev** [comment]
This does not appear to be reproducible, so I'm closing the issue. In case it is still a problem, feel free to reopen this with a sample.
