### ISSUE TITLE
Feature request: Add AngularJS data to grid PDF template

### ISSUE THREAD

**Issue by rmorrise** [telerik/kendo-angular2#133]
On the Kendo Grid control, when I configure the PDF template, give me a way to provide additional data aside from the built-in export parameters.

If I am using the Grid in the context of an AngularJS component, the Grid should have a way to show data from the parent component in the export template. For example, if I am exporting grid data that belongs to a particular customer, I should be able to display the customer's name and address in the generated PDF (even though they are not columns in the grid).

**Comment by tsvetomir** [comment]
This sounds like a feature request for **Kendo UI for jQuery**, specifically for its AngularJS integration. Please, file a request for this feature on its [UserVoice portal](http://kendoui-feedback.telerik.com/forums/127393-kendo-ui-feedback).

Closing the issue, as this repo covers only the Kendo UI for Angular 2 suite.
