### ISSUE TITLE
How should we prefix the template directives for DropDowns

### ISSUE THREAD

**Issue by valchev** [telerik/kendo-angular2#134]
Currently the template directives does not have a prefix which will most certainly cause conflicts in real projects.

What prefix should we add?

**Suggestion 1**: `kendo<ComponentName><Type>Template`

In order to reduce the confusion the template directive will have multiple selectors. For example `kendoDropDownListHeaderTemplate`, `kendoAutoCompleteItemTemplate`, `kendoMultiSelectFooterTemplate` and etc.

**Suggestion 2**: `kendo<PackageName><Type>Template`

A bit shorter, no multiple selectors, may confuse the user. For example `kendoDropDownsHeaderTemplate`, `kendoDropDownsItemTemplate`, etc.

What do you think?

cc @tsvetomir @petyosi @rkonstantinov @rusev @ggkrustev

**Comment by ggkrustev** [comment]
Although extremely verbose, I would vote for **Solution 1**. Thus every component will have a dedicated `selector`. Thus the directives usage will be more intuitive, e.g. kendoAutoComplete{DirectiveName}.

The second option is plausible, but thus we can have only one {directive name} per package. I am not sure whether this is a limitation or feature, but I 'feel' that Solution 1 would be better.

**Comment by petyosi** [comment]
I find Solution 1 more understandable, too.

**Comment by rusev** [comment]
I vote for Suggestion 1, too.

Suggestion 2 might cause some confusion, especially if the the context is different across different components. This will also complicate documentation for such directives.

**Comment by rkonstantinov** [comment]
Solution 1 gets my vote.

**Comment by valchev** [comment]
Ok, I will implement **solution 1**
