### ISSUE TITLE
PDF Export

### ISSUE THREAD

**Issue by charsleysa** [telerik/kendo-angular2#135]
Hi all,

We are currently looking at using Kendo UI for Angular 2 and I am wanting to know where PDF export sits on the Roadmap.

We are wanting something like this PDF Export customization example: https://demos.telerik.com/kendo-ui/pdf-export/page-layout

Any info would be much appreciated.

Cheers!

**Comment by petyosi** [comment]
Hi @charsleysa,

thank you for contacting us. PDF Export is something that we are looking into, but not set in stone for the next iteration. I may suggest that you post your request in [our feedback portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback). Based on the interest, we may consider prioritizing it.
