### ISSUE TITLE
Nth nested Grids

### ISSUE THREAD

**Issue by charsleysa** [telerik/kendo-angular2#136]
Hi all,

Currently playing around with the grids and it seems I can't nest grids past 1.

Anytime I try to nest grids it uses the innermost kendoDetailTemplate.

Is this a bug or am I just doing things wrong?

Any help would be much appreciated.

Cheers!

**Comment by KirilNN** [comment]
@charsleysa - you should nest the Grids using separate components for each of them, same as in this demo:

http://www.telerik.com/kendo-angular-ui/components/grid/hierarchy/
