### ISSUE TITLE
Templates for PanelBar using Items Collection Don't work

### ISSUE THREAD

**Issue by tregarick** [telerik/kendo-angular2#137]
In the documentation it says you can specify templates to render the content when using the items collection however this doesn't work.  To replicate just press the Run Code on Kendo UI documentation page in the Templates section.  The example should render a div saying 'Custom Template:' but when you run it is doesn't work.

**Comment by KirilNN** [comment]
The demo looks broken and we need to fix this. However the functionality is there, check this [plunkr](http://plnkr.co/edit/O656q7sXAck1cruYlwIz?p=preview)

**Comment by tregarick** [comment]
Brilliant thanks KirilNN.  Looks like 'kendo' is just missing from the template directive should have spotted that.

**Comment by KirilNN** [comment]
I will leave the issue open, until we fix the documentation.
