### ISSUE TITLE
Cannot stop Popup Control from Animating

### ISSUE THREAD

**Issue by tregarick** [telerik/kendo-angular2#138]
I have the following kendo-popup (Version 0.14.5 re-installed latest version).  But even thought animate is set to false the box always slide animates in from the top.  I have been unable to replicate in Plunker and I have changed the template so I know it's not using older markup without the animate.

```
<kendo-popup *ngIf="searchResults" [animate]="false" [anchor]="anchor" [popupClass]="'isl-popup'">
        <div class="isl-panelbar">
            <kendo-panelbar [items]="searchResultsModel">
                <template kendoPanelBarItemTemplate let-dataItem>
                    <table>
                        <thead *ngIf="dataItem.content.hasAttrHeaders">
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th *ngFor="let header of dataItem.content.attrHeaders">{{header}}</th>
                            </tr>
                        </thead>
                        <tr *ngFor="let item of dataItem.content.items">
                            <td>{{item.id}}</td>
                            <td>{{item.name}}</td>
                            <td *ngFor="let attr of item.attrs">{{attr}}</td>
                        </tr>
                    </table>
                </template>
            </kendo-panelbar>
        </div>
    </kendo-popup>
```

**Comment by ggkrustev** [comment]
Hi @tregarick,
The animation you are referring to is initiated by the PanelBar itself:
- http://screencast.com/t/KrpZHijGl

If the root tabs are collapsed, then there is no animation:
- http://screencast.com/t/9GlZVR14bTcy

[*this is the test application that I used*](https://github.com/ggkrustev/ng2-test-demo/tree/panelbar-in-popup)

The described 'initial panelbar animation' is a known bug that is already reported and will be fixed soon.
