### ISSUE TITLE
Install Data Query dependency with Grid

### ISSUE THREAD

**Issue by burkeholland** [telerik/kendo-angular2#143]
Right now, the Kendo UI Grid depends on the `kendo-data-query` package in order to work. This  is listed in the docs, but easy to look over. It seems more logical the Grid would resolve and install it's own dependencies.

I'm sure there is a good reason why this doesn't work that way already that I simply don't understand.

**Comment by rkonstantinov** [comment]
The `kendo-data-query` package is not proprietary to the Grid. The intention is that it could be used separately or with other components. This is why it is set as a peer-dependency. Think something like rxjs package ;)

**Comment by tsvetomir** [comment]
Still, we can update the [Installation](http://www.telerik.com/kendo-angular-ui/components/grid/#toc-installation) article to include the `@progress/kendo-data-query` package. Otherwise it would be too easy to miss.

**Comment by burkeholland** [comment]
In my experience, the Grid won't function without the `kendo-data-query` package. With the Angulage CLI, webpack will throw an error both on the CLI and in the browser. Is the Grid expected to function without the data query package?

**Comment by tsvetomir** [comment]
No, the Grid is not expected to function without it. The Getting Started article has been updated to the following installation command:

`npm install --save @progress/kendo-angular-grid @progress/kendo-data-query`

P.S. It's not published yet.

**Comment by burkeholland** [comment]
If the Grid won't work without the data-query package, it seems like it should be a child dependency instead of a peer. I worry that developers will fall into the same mistake I did which is assuming that the grid is broken instead of reading the docs.

**Comment by tsvetomir** [comment]
We can't give up the semantics of peer dependencies for what is essentially an usability issue of NPM itself. In fact, NPM < 3 [used to install](https://github.com/npm/npm/blob/master/doc/files/package.json.md#peerdependencies) these automatically. Future versions [might address this](https://github.com/npm/npm/issues/11213). Yarn [might do that](https://github.com/yarnpkg/yarn/issues/1503) as well.

Marking kendo-data-query and similar packages, such as kendo-drawing as direct dependencies is certainly a possibility. It will solve the problem you're having, but will create scenarios where you load multiple concurrent versions of these dependencies. This is most certainly **not what the user wanted**.

We must not forget that NPM is a Node package manager - having multiple copies loaded is perfectly fine in Node, not so much in the browser.

**Comment by burkeholland** [comment]
I understand now. Thank you for the schooling there on NPM. I suppose the best we can do in the meantime is make it overly and abundantly clear in the documentation that you need to have the `data-query` package. 

Closing for now as I think this has been sufficiently discussed.

**Comment by tsvetomir** [comment]
Using Yarn shouldn't be a problem with #712 in effect.
