### ISSUE TITLE
Unable to set custom class on a Button

### ISSUE THREAD

**Issue by tsvetomir** [telerik/kendo-angular2#146]
The [standard bindings](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#other-bindings) don't appear to work, see [plunkr](http://plnkr.co/edit/fXxbhbXx9FhKz8AvIanL?p=preview):

    <button class="foo">Button</button>
    <button [class.foo]="true">Button</button>

**Comment by v-r-sankar** [comment]
The ngStyle directive seems to work with Kendo angular 2 button, but ngClass directive is not working.
