### ISSUE TITLE
DropDownList markAsTouched called incorrectly

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular2#147]
In the DropDownList constructor it calls method subscribeEvents and in that method in subscibes to the document click event and when the document click event fires, it calls this components componentBlur method which calls the markAsTouched method. So what is happening is when i click anywhere on my document the DropDownList automatically says that it has been touched, which raises validation messages.

**Comment by djarekg** [comment]
Sorry, i am using version 0.20.2

**Comment by valchev** [comment]
@djarekg Thanks for pointing this out. I will take a look and provide a fix in the next few days.

**Comment by djarekg** [comment]
Awesome...thank you

**Comment by valchev** [comment]
@djarekg :)

Note that the fix is in a branch that is not yet merged in production. I will close the issue after branch is merged.
