### ISSUE TITLE
node_modules directory is being included with npm packages

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular2#15]
The node_modules directory is being included in the npm packages.

**Comment by underlog** [comment]
Seems strange - which package do you refer to? This should not happen according to NPM docs. 

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by djarekg** [comment]
The grid package

**Comment by underlog** [comment]
To investigate this further, we need the steps to reproduce and NPM version. Will re-open the issue once you submit these; thank you!
