### ISSUE TITLE
How to use em or rem as a unit to set the column width ?

### ISSUE THREAD

**Issue by nedhsieh** [telerik/kendo-angular2#151]
How to use em or rem as a unit to set the column width ?

and the grid don't auto expand full screen ?

**Comment by rkonstantinov** [comment]
I'm afraid that `column.width` option currently supports only pixel values.

**Comment by nedhsieh** [comment]
I found the file： "\node_modules\@progress\kendo-angular-grid\dist\npm\js\col-group.component.js",
and modify row 94 [style.width.px]=\"column.width\" to [style.width.rem]=\"column.width\",
it's work, but I do not know the other will not be affected.

**Comment by rkonstantinov** [comment]
Indeed, you could change it to `rem`. However, this means that only `rems` will work.

**Comment by tsvetomir** [comment]
The problem with relative units is that the Grid needs to know the exact size in pixels during rendering. This is required for features such as frozen rows and virtual scrolling.

Figuring out the rem-to-pixel ratio requires a live DOM, something we don't have access to initially or during server rendering.

With that in mind, I'll close this issue as nice to have, but impractical.
