### ISSUE TITLE
Getting Started Page Style Instructions

### ISSUE THREAD

**Issue by ssatterfield** [telerik/kendo-angular2#152]
It appears the **Getting Started** document on the Telerik site is out of date.  On this page...

[http://www.telerik.com/kendo-angular-ui/getting-started](http://www.telerik.com/kendo-angular-ui/getting-started)

In the **Add the Styles** section step 1 it has you install the default Kendo UI theme with...

`npm install -S @telerik/kendo-theme-default`

When following these directions the theme did not install in the node_modules folder indicated in step 2.  

`@import "~@telerik/kendo-theme-default/styles/packages/all";`

To fix the issue I used the import statement below and it worked as expected.

`@import "~@progress/kendo-theme-default/dist/all";`

### Details:

I followed every step in the **Getting Started** page including adding the Telerik registry using the steps shown under **Installation**.  I am a customer and have access to the commercial products which may have affected what package I got when I installed the theme?  I'm not sure.

My PC is running Windows 10 x64 and my version of npm is 3.10.9.

**Comment by gyoshev** [comment]
Both theme names should be functional for the time being. The theme has recently been renamed, and the official name will be `@progress/kendo-theme-default` at the time of the January release, but the instructions in the Getting Started help topic are still relevant. I just went through the getting started help topic and the theme seems to be installing correctly.

Can you please confirm, does the folder `node_modules/@telerik/kendo-theme-default` exist after `npm install -S @telerik/kendo-theme-default`?

The difference between `styles/packages/all` and `dist/all` is that the first is a SCSS file, and the latter a CSS file. Importing the SCSS allows you to customize the theme through SCSS variables, directly from your application. If including the SCSS is causing trouble, it may be that the application has not been created with the `--style=scss` parameter in step 2 of *Adding the components*. This can be verified in `angular-cli.json`, in the `defaults.styleExt` parameter.

**Comment by ssatterfield** [comment]
The odd thing is I followed the same instructions on a different computer and that time the path matched the website.

On my desktop running Windows 10 the installation matched what I described above.  On my laptop running Windows 7 it matches the website's directions.  I just thought you might want to know in case others ran into the same issue I did.

Thanks for replying so quickly!

**Comment by gyoshev** [comment]
We have updated the installation instructions after the theme name change and tested the installation in Windows 10, seems to be working. If you are encountering problems with the installation of the theme under its new name, please open a new issue.

**Comment by anvlkv** [comment]
Hi! Probably something have changed...
[https://www.dropbox.com/s/or0jltzxu0c4hpq/Screen%20Shot%202017-02-01%20at%2011.24.18.png?dl=0](screenshot)

I can't see any kendo styles applied to <h1> tag

**Comment by gyoshev** [comment]
@anvlkv our aim for the kendo styles is to be non-obtrusive, so they won't apply styles to HTML elements by default. This has always been the case, application styling is left to the developer.

**Comment by anvlkv** [comment]
Hey that is great, but I was trying to follow the getting started guide and didn't see any classes or attributes on h1 there neither I did in docs for themes.
