### ISSUE TITLE
Grid with in-line editing

### ISSUE THREAD

**Issue by coder925** [telerik/kendo-angular2#157]
Is in-line row editing within the Grid’s cells a feature planned for any of the upcoming releases?

According to [the documentation](http://www.telerik.com/kendo-angular-ui/components/grid/editing/) a built-in form is planned but I assume that will be in a _modal popup dialog_.

After looking though [the roadmap](http://www.telerik.com/kendo-angular-ui/roadmap/) and [the feedback portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback) I have been unable to find any information about inline row editing. Any feedback on this feature is appreciated. Thanks!

**Comment by rusev** [comment]
We are currently working on API for inline editing similar to the [Kendo UI Grid](http://demos.telerik.com/kendo-ui/grid/editing-inline). 

Editing functionality will be coupled with angular forms as they provide validation and model state tracking out of the box.

**Comment by coder925** [comment]
Great to hear that the same kind of inline editing capabilities are coming!

When do you think a first beta version of that feature will be available?

**Comment by rusev** [comment]
Inline editing will be demonstrated in upcoming couple weeks.

**Comment by DotNetPart** [comment]
Will it get into RC.0?

**Comment by rusev** [comment]
Yes, inline editing will get into RC.0.

**Comment by tsvetomir** [comment]
The [Editing](http://www.telerik.com/kendo-angular-ui/components/grid/editing/) section has been published.

Please feel free to reopen if you have any feedback.
