### ISSUE TITLE
How to set position of k-dialog ?

### ISSUE THREAD

**Issue by nedhsieh** [telerik/kendo-angular2#161]
I want to set position of dialog, like { top: 150px; left: 30px; }

How can I do ?

and can I use the mouse to drag it? How to do?

**Comment by gyoshev** [comment]
The dialog does not support setting its position, nor dragging. These behaviors are customary for the window component, which has been [requested on UserVoice](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback/suggestions/17597812-window-component).
