### ISSUE TITLE
ComboBox filtering wiping result and input box

### ISSUE THREAD

**Issue by mzanniebannie** [telerik/kendo-angular2#162]
I am currently using the ComoBox Filtering functionality in my Angular2 application and I noticed a strange behavior when using in the input. The inputbox gets wiped out when searching on certain conditions. We are using the combobox filtering as an auto complete to suggest search terms, but if none exists we will search on the inputted text. This bug is preventing us from doing so. 

The plunker below is the same one used on the ComboBox Overview page, filtering section

http://plnkr.co/edit/UUhqIjLaKNtvtnGFcond?p=preview

Steps to Reproduce Behavior:
1. Without opening dropdown, proceed to type "Med" -> dropdown shows only Medium (Correct behavior)
2. Add an additional "d" to existing search so search string reads "Medd" -> dropdown result disappears (correct behavior) but the "Medd" in the search box gets wiped and now input box is empty.
3. Try click on dropdownlist arrow -> dropdownlist does not open
4. Focus back into input box and press backspace 4 times, to simulate erasing "Medd", try clicking dropdownlist arrow -> dropdownlist does not open

Additional Behavior:
1. Type "e" into input box, 2 results appear.
2. Type another "e" into input box, so input string should be "ee", input box gets wiped and dropdownlist is displaying no results.

Observations:
The input box allows any string as long as no matches are found.  String like "funtime" is not wiped from the input box during filter because the first letter "f" is not in any result.
To get dropdownlist to display all data again, user must enter a letter that exists in a search result and press backspace. For example: typing "e" then pressing backspace will show all 3 options again and clicking on the dropdownlist arrow now shows 3 options.

**Comment by tapopov** [comment]
Thanks for the detail report @mzanniebannie! We will look into it.

**Comment by tapopov** [comment]
Hey @mzanniebannie,

We've prepared a fix that will be included in a build later today.
