### ISSUE TITLE
Miss alignment of Tab strip's first tab button

### ISSUE THREAD

**Issue by olakara** [telerik/kendo-angular2#164]
Plunker: http://plnkr.co/edit/x66cGVvtdbxOlAgTfsUr?p=preview

The same issue can be seen in documentation example as well.. In the tab strip component, the first tab's left border is not aligned with the tab content's border.

![untitled](https://cloud.githubusercontent.com/assets/570905/21743291/8562c176-d518-11e6-893b-1c31e5d84de3.png)

Above is the screen shot of the bug

**Comment by zdravkov** [comment]
Thank you for reporting the issue. It is known bug that is already addressed and it will be fixed for the official upcoming release.
