### ISSUE TITLE
Virtual scrolling

### ISSUE THREAD

**Issue by danamAlgotec** [telerik/kendo-angular2#166]
There is some unexpected visual behavior when you scroll the Grid:
>  The scroll box jumps up when a new page loads.  

**steps:**
1. Open the virtual scrolling example. 
2. Change the data size to 200 row.
this.data = this.createRandomData(200);
3. Run
2. Scroll down
3. When scrolling the scroll box jumps up. 

**browser version:** chrome 55.0.2883.87 m & explorer 11.0.9600.18537
**link:**  http://plnkr.co/edit/wwvpghM4zTdZURFhTR2q?p=preview

**Comment by rusev** [comment]
This seems same [this issue](https://github.com/telerik/kendo-angular2/issues/154).
