### ISSUE TITLE
the virtual grid cover the dialog in the same page

### ISSUE THREAD

**Issue by lucifercha** [telerik/kendo-angular2#169]
First my english is not very well，i am not sure whether i can describe my question clearly，sorry.
I have a virtual grid and a dialog in the same page,when i click a button to show the dialog,i found the whole grid cover the dialog,include the grid head and the grid body,like this:
![image](https://cloud.githubusercontent.com/assets/3349701/21791585/afe3346e-d71e-11e6-8ba2-967660d5899a.png)
and the code is like this:

`<kendo-dialog title="监控设置" *ngIf="dialogOpened" (close)="close('cancel')">
    <kendo-dialog-actions>
        <button kendoButton (click)="close('yes')" primary="true">yes</button>
        <button kendoButton (click)="close('no')">no</button>
    </kendo-dialog-actions>
</kendo-dialog>`

`<kendo-grid [data]="view"
            [scrollable]="'virtual'"
            [selectable]="true"
            [height]="200"
            [rowHeight]="36"
            [skip]="skip"
            [pageSize]="pageSize"
            (pageChange)="pageChange($event)">
    <kendo-grid-column field="department" title="department" width="80"
                       [style]="{'border-bottom-width': '1px'}">
    </kendo-grid-column>
</kendo-grid>`

and if i change the position of dialog and grid，only the grid body cover the dialog ，like this:
![image](https://cloud.githubusercontent.com/assets/3349701/21791545/7618370c-d71e-11e6-8d7b-32e4e666cc5a.png)

is anybody can help me?

**Comment by lucifercha** [comment]
i think may be some css mistakes

**Comment by lucifercha** [comment]
`.k-grid-virtual .k-grid-content>table {
	z-index:0;
}`
change the style ,and it worked for me

**Comment by gyoshev** [comment]
While the above `z-index` works, it is cleaner to set it to the dialog component. This has been fixed in the theme package, versions **2.1.0** and above.

Please note that the theme package has been renamed to `@progress/kendo-theme-default` -- see the updated instructions in the [Getting Started help topic](www.telerik.com/kendo-angular-ui/getting-started/) to install the latest version of the theme.

**Comment by lucifercha** [comment]
@gyoshev [Getting Started help topic](https://github.com/telerik/kendo-angular2/issues/www.telerik.com/kendo-angular-ui/getting-started/) is a 404 page

**Comment by tsvetomir** [comment]
Fixed, sorry!
