### ISSUE TITLE
When Kendo-combobox valuePrimitive = true,  OnValueChange trigger twice

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular2#172]
In kendo-combobox, the valuePrimitive property when set to true, the OnValueChange is triggered twice.

Steps:
1) Select an item
2) Click in some other part of the page.(eg just next to combobox).
-OnValueChange triggers again.

Kindly look at the [Plunker](http://plnkr.co/edit/JwdRmBSjxqyKG3AbWW5r?p=preview) more info

**Comment by tapopov** [comment]
Hi @skyfremen, 

Thanks for the report. we will look into it shortly.

**Comment by skyfremen** [comment]
Hi, is the issue fixed therefore marked as closed?

**Comment by tapopov** [comment]
Hi @skyfremen 

We've just introduced a fix for the issue, which should be available in the next release.

**Comment by skyfremen** [comment]
@tapopov Noted thanks
