### ISSUE TITLE
Setting majorUnit on a line/column chart axis has no effect

### ISSUE THREAD

**Issue by Yves-Be** [telerik/kendo-angular2#173]
Setting the majorUnit on the y-axis like this has no effect to the axis of a line- or column chart:
```
          <kendo-chart-y-axis>
            <kendo-chart-y-axis-item majorUnit="2">
              </kendo-chart-y-axis-item>
            </kendo-chart-y-axis>
```

http://plnkr.co/edit/hbEuThgigavRnfV5cyNX?p=preview

It does work for scatter charts, as seen in the plunker.

**Comment by tsvetomir** [comment]
Categorical charts such as line or column use a value-axis, not y-axis. See the [updated snippet](http://plnkr.co/edit/DGxMydVa9mXxA6NE6pwq?p=preview).
The idea is to use the same configuration for bar, bullet, etc. where the value axis is in fact an X axis.


The documentation topic on axes is not available yet, but this will be explained there.
