### ISSUE TITLE
Cannot find module "[...]/node_modules/@progress/kendo-angular-upload/dist/npm/css/main.css"

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular2#177]
Since I updated the component to `v0.12.0`.

    ERROR in multi styles
    Module not found: Error: Can't resolve '[...]/node_modules/@progress/kendo-angular-upload/dist/npm/css/main.css' in '[...]/node_modules/angular-cli/models'
     @ multi styles

**Comment by Raisolution** [comment]
Hi @maximedupre,

The component styles are now served from the _kendo-theme-default_ package. Check the following [documentation section for details](http://www.telerik.com/kendo-angular-ui/getting-started/#toc-adding-the-styles).

**Comment by maximedupre** [comment]
Thanks for the help!
