### ISSUE TITLE
How to dynamically set Label property on kendo Charts ?

### ISSUE THREAD

**Issue by jiveshrelhan** [telerik/kendo-angular2#178]
`<kendo-chart renderAs="canvas">
                    <kendo-chart-series-defaults type="column" [labels]="{visible:true}"** [stack]="true" ></kendo-chart-series-defaults>
                    <kendo-chart-series>
                        <kendo-chart-series-item  ,......"></kendo-chart-series-item>
                    </kendo-chart-series>`

Dynamically changing [labels]="{visible:false}".

**Comment by jiveshrelhan** [comment]
@Raisolution

**Comment by tsvetomir** [comment]
That should be easy, just bind the visibility to a component field:

```ts
<kendo-chart-series-defaults type="column" [labels]="{ visible: labelsVisible }">

...

export class AppComponent {
  public labelsVisible: boolean = true;
  
  public toggleLabels() {
    this.labelsVisible = !this.labelsVisible;
  }
}
```

You can also use the dedicated [kendo-chart-series-defaults-labels](http://www.telerik.com/kendo-angular-ui/components/charts/api/SeriesDefaultsLabelsComponent/) component, if it suits your code style:
```
<kendo-chart-series-defaults type="column">
  <kendo-chart-series-defaults-labels [visible]="labelsVisible">
  </kendo-chart-series-defaults-labels>
</kendo-chart-series-defaults>
```
