### ISSUE TITLE
Typescript Source?

### ISSUE THREAD

**Issue by alindsay55661** [telerik/kendo-angular2#18]
Will this be available in the commercial offering? We are commercial clients and were hoping to start using Kendo on our new Angular2 project but we definitely need access to the source in order to do that.

**Comment by Tenmak** [comment]
Do you mean access to the node package or access to the source code ? 
You should check that out if you don't have access to the packages.

**Comment by alindsay55661** [comment]
I mean access to the Typescript source code.

**Comment by KirilNN** [comment]
Hi @alindsay55661,

Can you please tell us what you want to do with the source code? For building the package we use internal modules, that are not publicly available, so providing the source code will give you only `readonly` capabilities.

**Comment by alindsay55661** [comment]
Yes, we have extended and modified Kendo jQuery components in our current projects. If we are to continue using Kendo now that we are migrating to Angular 2, we need the ability to modify your components as they aren't all exactly what we need.

**Comment by underlog** [comment]
@alindsay55661 - this sounds interesting. How do you deal with upgrades to the newer versions?

**Comment by alindsay55661** [comment]
We only upgrade about once a year. Also, we try to keep modifications to a minimum and well documented. We also make a copy of the component and keep the original for reference. It's not ideal, but it is faster than writing our own.

**Comment by underlog** [comment]
Thank you for the input. We will give this scenario some thought. To be honest, what you describe will be a lot more difficult to do with Kendo UI for Angular 2. Now that we have moved to NPM modules, we will move and refactor stuff around files as the components grow a lot more. We are no longer bound to the files convention we had previously. Applying patches to these may turn into an exercise of frustration. 

Finally, I hope that we will be able to ship components that don't require the source code modification to fit your scenario.

**Comment by tellxp** [comment]
However, "Kendo for A2 shoud be opensource", todd motto said on twitter.

**Comment by tsvetomir** [comment]
There are no plans to open source the A2 suite or parts of it. I couldn't find a reference to the particular tweet, but I'm certain this was some innocent misunderstanding.

**Comment by toddmotto** [comment]
@tellxp Hey! I think I was incorrect on this one - my apologies!

**Comment by tsvetomir** [comment]
We have two options at the moment:

- Package each source repo in a ZIP and make it accessible through My Account
- Provide mirrors of the source repos, accessible over HTTPS with your Telerik credentials

We'll do either one of those or both. It'll take some more time to make a decision due to legal and technical issues.

**Comment by tsvetomir** [comment]
Just a quick update. We still don't have a good solution due to the complexity of building the network of projects from source.

We're ready to provide the full source to any licensed user _on demand_. Feel free to contact us via the ticketing system.

**Comment by ElRoberto538** [comment]
For anyone still looking for this, you can now access the source here:

https://www.telerik.com/kendo-angular-ui/components/installation/source-code/#toc-submitting-your-credentials

**Comment by tsvetomir** [comment]
Thanks for posting the link here, @ElRoberto538
