### ISSUE TITLE
Group By drag & drop seems to be broken in IE11

### ISSUE THREAD

**Issue by Beachovic** [telerik/kendo-angular2#180]
Hi,

I couldn't find any previous issues mentioning this. I noticed that with the sample on your webpage regarding grouping, if I try to drag&drop a column to the group by area the header just stays frozen and no grouping is happening. In Chrome it is working correctly.
Here is a plnkr which is just a copy of the sample on your webpage:
http://plnkr.co/edit/9W89eqSPEo0kY8aOBJgi?p=preview

Thanks

**Comment by rkonstantinov** [comment]
Thanks for the report. We managed to identify the cause for the error and the fix will be included in the next package version.
