### ISSUE TITLE
Kendo breaks Bootstrap inside their widgets?

### ISSUE THREAD

**Issue by Etchelon** [telerik/kendo-angular2#19]
Hello,
I'm using a KendoTabstrip in my project and the content of a tab, which was previously not inside your widget, broke. I noticed this style:
`
    .k-widget, .k-widget *, .k-widget *::before {
        box-sizing: content-box;
    }
`
Since Bootstrap defaults to border-box for everything... does it mean we can't use Bootstrap inside your widgets without manually adjusting the CSS?

**Comment by gyoshev** [comment]
Yes, at this time you need to adjust the box-sizing of nested Bootstrap elements inside widgets, with a few lines of CSS. Here is [the explanation and a workaround](http://docs.telerik.com/kendo-ui/third-party/using-kendo-with-twitter-bootstrap#nest-widgets-and-bootstrap-grid-layout).

**Comment by gyoshev** [comment]
That said, the ideal behavior would be not to touch styles of user-defined content, so we'll attempt to remove the styles, and use box-sizing only where we need it, preserving the bootstrap layout. /cc @inikolova @joneff

**Comment by joneff** [comment]
For kendo-theme-bootstrap `box-sizing` is fixed via https://github.com/telerik/kendo-theme-bootstrap/commit/b04892fcee3201fe474628b846ac20c6fb7231ea

**Comment by gyoshev** [comment]
The `box-sizing` has been fixed in kendo-theme-bootstrap with the above commit. Container widgets should properly display bootstrap grids. In case of any issues, please report them to the concrete theme repo.

**Comment by Etchelon** [comment]
Thanks, I won't be able to test it anytime soon, when I do I'll come back at you
