### ISSUE TITLE
Kendo-theme-default is overriding default style of  <fieldset><legend>

### ISSUE THREAD

**Issue by skyfremen** [telerik/kendo-angular2#193]
When I applied the theme, it overrides the default styling of 
`<fieldset><legend></legend></fieldset>`

Please view the plunker for the differences.
[Plunker - Without kendo-theme-default applied](http://plnkr.co/edit/miH4d31hzhkN8TYP7CoC?p=preview)
[Plunker- With kendo-theme-default applied](http://plnkr.co/edit/lSKFveF1UkV8FHShfsPS?p=preview)

**Comment by gyoshev** [comment]
@skyfremen thanks for reporting this, the above commit fixed this. If you want to use the Kendo fieldset styling, add the `k-fieldset` class.
