### ISSUE TITLE
DatePicker Missing

### ISSUE THREAD

**Issue by SoulTransfer** [telerik/kendo-angular2#194]
Dear KendoUI Team,

I am looking for the DatePicker Component which was meant to b released yesterday according to your roadmap and the newsletter. But I can't find it in the @progress/kendo-angular-Inputs repository!

-> How to get the new DatePicker?
-> Or.. when will it be released?

**Comment by EricSch** [comment]
Same here, waiting for it :)

Go KendoUI Team

**Comment by KirilNN** [comment]
Hi @SoulTransfer,

Thanks for the interest in Kendo UI!

We will not be releasing a DatePicker component, but two separate DateInput and Calendar components, they will be part of the kendo-angular-date-inputs package. 

Most probably the package that includes the Calendar will be released later today, and the DateInput component in the following weeks.

**Comment by tsvetomir** [comment]
Just to clarify, the Date/Time Picker is on the Roadmap for the May release.

**Comment by SoulTransfer** [comment]
@KirilNN thank you for the clarification and the lighting fast answer. Therefore, we will check back tomorrow. 
But I'm still wondering why the RC.0 was announced for the 17th if many components are not ready at this date but at a later point in time?

@tsvetomir - No. The Datepicker is part (according to: http://www.telerik.com/kendo-angular-ui/roadmap/) of RC.0

**Comment by KirilNN** [comment]
@SoulTransfer - apologies for not being able to deliver the components on time, but believe me we are doing our best to make them ready as soon as possible. The good thing is that using the NPM delivery, we can be really flexible in deploying features as soon as they are ready.

**Comment by petyosi** [comment]
Hi @SoulTransfer 

Kendo UI PM here - your observation is correct. Our initial intention was to develop the equivalent of the current Kendo UI DatePicker for R1 2017. Further down the road, we took into account a common request - support for masked date/time entry in the input part of the picker. This being said, we opted to develop the two DatePicker parts (DateInput and Calendar) separately, subsequently building a datepicker from them. Our roadmap was not updated accordingly, though. 

Like @KirilNN mentioned, The Calendar and the DateInput parts are coming soon. After that, we are going to look into the composite component. I think that the DateInput component should cover the date entry scenarios quite well in the mean time.

**Comment by squadwuschel** [comment]
@petyosi is it right that the datepicker and timepicker will not be ready in the May Release?

**Comment by petyosi** [comment]
@squadwuschel Actually, we are working towards making them available **before May**.

**Comment by pmangat** [comment]
Hey Kendo Team - Been a month since this update. Are datepicker and timepicker released?

Thank you.
