### ISSUE TITLE
Kendo Theme Default - Cant install 2.x

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular2#195]
When using npm cant 2.x theme. Npm error says only 1.x versions available.

**Comment by rusev** [comment]
We will need more details on the error you get. Attaching `npm-debug.log` file will also help in debugging this issue.

**Comment by gyoshev** [comment]
@djarekg the theme package name got changed between the 1.x and 2.x versions. The 2.x version is hosted on the (private) Progress NPM registry, like all other components, and is available under the name `@progress/kendo-theme-default` (in contrast to `@telerik/kendo-theme-default`, which is hosted on the official NPM registry). Please verify that the application lists the `@progress`-scope package in its package.json.

If the problem persists, please provide the details requested above.

**Comment by djarekg** [comment]
That was the issue. I was referencing @telerik and not @progress. Thank you.
