### ISSUE TITLE
toODataString works wrong

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular2#196]
```
state
Object {group: Array[0], skip: 20, sort: Array[0], take: 20}
```

called with `toODataString(state)`
gives `&$skip=20&&$top=20`

Our .NET WebApi controller has problem to parse the two "&&"

**Comment by rkonstantinov** [comment]
Thanks for the report. This will be addressed with the next version of the data-query package.

**Comment by rusev** [comment]
@EricSch version `0.3.5` should address the issue.
