### ISSUE TITLE
AOT build fails

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular2#197]
I'm using the latest versions of the grid, installed via
`npm install --save @progress/kendo-angular-grid @progress/kendo-data-query @progress/kendo-angular-intl
`
the output:
> ..
> +-- @progress/kendo-angular-grid@0.13.0
> +-- UNMET PEER DEPENDENCY @progress/kendo-angular-intl@0.9.0
> +-- @progress/kendo-data-query@0.3.4
> ..

When I run the aot build, angular throws an error:

> Error: Metadata version mismatch for module C:\xx/node_modules/@progress/kendo-angular-grid/dist/es/grid.module.d.ts, found version 3, expected 2
>     at StaticReflector.getModuleMetadata (C:\xx\node_modules\@angular\compiler\bundles\compiler.umd.js:25219:36)

I include others components in my project too, like dialog, popup, upload, buttons. But don't know the dependencies between them.

Thanks

**Comment by rusev** [comment]
What is the version of the Angular packages? Our AoT builds are running against 2.4.x and all seems to be working properly.

Have in mind that there was a _hidden_ breaking change in the `*.metadata.json` files between 2.2.x and 2.4.x versions of Angular. That seems like a possible reason for the issue based on the error message.

**Comment by tsvetomir** [comment]
Also, please note that @progress/kendo-angular-intl is also a peer dependency and [should be installed alongside the Grid](http://www.telerik.com/kendo-angular-ui/components/grid/#toc-installation).

`npm install --save @progress/kendo-angular-grid @progress/kendo-data-query @progress/kendo-angular-intl`

**Comment by EricSch** [comment]
Thank you.

    "@progress/kendo-angular-buttons": "0.14.5",
    "@progress/kendo-angular-dialog": "0.13.3",
    "@progress/kendo-angular-grid": "0.10.0",
    "@progress/kendo-angular-intl": "^0.7.0",
    "@progress/kendo-angular-popup": "0.15.0",
    "@progress/kendo-angular-sortable": "0.7.0",
    "@progress/kendo-angular-upload": "0.12.0",
    "@progress/kendo-data-query": "0.3.4",
    "@telerik/kendo-intl": "0.11.2",
    "@telerik/kendo-theme-bootstrap": "0.10.0",
    "@telerik/kendo-theme-default": "1.33.4",

this where my last working modules combination.

we are building against Angualr 2.3.x. Could that be the reason?

**Comment by rusev** [comment]
Yes Angular version is the issue. There was a breaking change in the compiler and now it produces metadata with **_version 3_**. The latest versions of our components is build against Angular _**2.4.x**_, so you will have to upgrade the version in your application too.

It's a bit unfortunate, as they claim no breaking changes between minor versions.

**Comment by tsvetomir** [comment]
Apologies for not reading your initial post carefully. You already include `@kendo-angular-intl` installed, the unmet peer dependency error you get is due to a bug - the latest version of the Grid doesn't reference the version of the Intl package. We'll fix this right away.

**Comment by EricSch** [comment]
thanks guys for all the input.

I hope Google will stick to his **Semantic Versioning** paper, was a very rough ride from Angular2 alpha until now.
