### ISSUE TITLE
Provide a caching solution for tabstrip content

### ISSUE THREAD

**Issue by KirilNN** [telerik/kendo-angular2#198]
Currently, the tabs of the Kendo UI TabStrip, will be detached from the DOM when another one is selected. This approach might not be optimal in cases like remote data loading, or intensive rendering - such as canvas. So we will investigate a solution, that will provide some optimization for such scenarios.

**Comment by KirilNN** [comment]
`keepTabContent` option has been introduced in order to accommodate the different rendering requirements. It should be available with version `0.19.0` and above.

cc @maximedupre

**Comment by maximedupre** [comment]
@KirilNN Thank you!!
