### ISSUE TITLE
DataViz Suite Preview Release

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-angular2#2]
Given the broad topic DataViz is, I think that we will need to come up with some more concrete details on our initial plan. 

Owned by @danielkaradachki @tsvetomir

**Comment by tsvetomir** [comment]
Design goals:
- Allow configuration through both configuration components (samples on the way) and POJOs
- Support one-way bindings and structural directives
- Strongly typed properties
- Reuse the implementation of the existing Kendo UI suite via two additional packages:
  - A public `@progress/kendo-drawing` package, also suitable for standalone use
  - An internal `@progress/kendo-charts` package not meant for direct consumption by users
- Drop dependency on jQuery

Some important differences with the Kendo UI for jQuery DataViz suite:
- Themes are now configured with SASS variables. There are no chart specific themes.
- The `template` properties of series labels, etc. are renamed to `content` and accept only functions that return plain text. This is to avoid confusion with Angular templates.

**Comment by tsvetomir** [comment]
## Chart Component

This is an Angular version of the [Kendo UI Chart for jQuery](http://docs.telerik.com/kendo-ui/controls/charts/overview) component.
It will be the first DataViz component to be published in the Kendo UI for Angular suite.

### Features
Planned features for the Beta release include:
- Support for different series types - bar, line, scatter, pie, donut, etc.
- Pan and zoom
- Events for actions such as series click, pan and zoom

The following features are unlikely to ship for the Beta release, but will follow in later releases:
- Tooltip (blocked by #9)
- Selection
- PDF Export

### Sample Usage

In the example below we demonstrate a few basic features
- Configuration component structure
- Use of structural directives on the configuration components
- Binding properties to both inline values and component fields

```js
import 'core-js/es6';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';

import { Component } from '@angular/core';
import { bootstrap } from '@angular/platform-browser-dynamic';
import { CHART_DIRECTIVES } from '../src/main';

@Component({
  selector: 'my-app',
  template: `
    <kendo-chart>
      <kendo-chart-legend *ngIf="legendVisible" background="green"
                           [border]="{ width: 2, color: 'red' }">
      </kendo-chart-legend>
      <kendo-chart-series>
        <kendo-chart-series-item *ngIf="seriesVisible"
                                  type="line" [data]="[1, 2, 3]">
        </kendo-chart-series-item>
      </kendo-chart-series>
    </kendo-chart>
  `,
  directives: [CHART_DIRECTIVES]
})
class AppComponent {
  private legendVisible: boolean = true;
  private seriesVisible: boolean = true;

  public toggleSeries(): void {
    this.seriesVisible = !this.seriesVisible;
  }
}

bootstrap(AppComponent);
```

### Data Binding
Series and other chart elements can be bound to primitive values, models and observables (via async pipe). The snippet below demonstrates the basic bindings as they can be applied to chart series.

```js
import 'core-js/es6';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';

import { Component } from '@angular/core';
import { bootstrap } from '@angular/platform-browser-dynamic';

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/interval';
import 'rxjs/add/observable/from';
import 'rxjs/add/operator/map';

import { CHART_DIRECTIVES } from '../src/main';

interface MyModel {
  value: number;
}

@Component({
  selector: 'my-app',
  template: `
    <kendo-chart [transitions]="false">
      <kendo-chart-series>
        <kendo-chart-series-item name="Bound to Array"
                                 [data]="[0.1, 0.75]">
        </kendo-chart-series-item>
        <kendo-chart-series-item name="Bound to Array field"
                                 [data]="seriesData" field="value">
        </kendo-chart-series-item>
        <kendo-chart-series-item name="Bound to Observable"
                                 [data]="data$ | async">
        </kendo-chart-series-item>
      </kendo-chart-series>
    </kendo-chart>
  `,
  directives: [CHART_DIRECTIVES]
})
class AppComponent {
  private seriesData: MyModel[] = [{ value: 0.5 }, { value: 1 }];

  private data$: Observable<number[]> = Observable.from([[]]);

  public constructor() {
    this.data$ = Observable.interval(100)
                 .map(i => [Math.random(), Math.random()]);
  }
}

bootstrap(AppComponent);
```

### Supported Browsers
Target is IE9+ and all modern browsers. The legacy VML rendering mode for IE6-8 will be dropped.

### Accessibility
No accessibility features are planned.

**Comment by underlog** [comment]
The charts package is published at http://www.telerik.com/kendo-angular-ui/components/charts/
