### ISSUE TITLE
Using kendo for jquery css missing styles 

### ISSUE THREAD

**Issue by djarekg** [telerik/kendo-angular2#20]
For example I'm using the css files provided from the kendo for jquery and for the ng2 grid, the style k-grid is missing the display block style. Adding this style fixed te the issue but it seems there are a few styles missing for the ng2 version.

**Comment by KirilNN** [comment]
@djarekg  The rendering for the new Angular 2 components is different from the classic Kendo UI widgets, therefore the old themes are incompatible.

**Comment by djarekg** [comment]
Are there any other themes available besides the default and if not when are more being planned?
