### ISSUE TITLE
kendoCellTemplate directive broken going from ^0.8.2 to ^0.13.3

### ISSUE THREAD

**Issue by dcparsons** [telerik/kendo-angular2#201]
This is likely a "by design" issue.   Prior to upgrading, a column definition within the kendo-grid might look like this:

```
<kendo-grid-column field="IsFoo" title="Is Foo">
	<template kendoCellTemplate let-dataItem>
		{{dataItem.IsFoo ? "Yes" : "No"}} 
	</template>
</kendo-grid-column>
```

This works as expected: if IsFoo is true 'Yes' is displayed in the column otherwise 'No' is displayed.  After I upgraded to 0.13.3 I experienced two problems:

- The field  property on kendo-grid-column became case sensitive.
- Content in the template was ignored and instead the databound value was simply printed to the screen.  

For the second problem I couldn't figure out what was going on because I didn't have any errors in my Chrome console and my overall page template displayed fine.  I checked the [changelog](http://www.telerik.com/kendo-angular-ui/components/grid/changelog/) for the grid but I didn't see any entries for what I was experiencing.  After I revisited the [configuration samples](http://www.telerik.com/kendo-angular-ui/components/grid/configuration/) I noticed that kendoCellTemplate directive had become kendo**Grid**CellTemplate.   

Is there any reason why using the incorrect directive didn't throw an exception?

**Comment by tsvetomir** [comment]
> The field property on kendo-grid-column became case sensitive.
I was under the impression that [this was always the case](http://angularjs.blogspot.bg/2016/02/angular-2-templates-will-it-parse.html) with Angular 2

> Is there any reason why using the incorrect directive didn't throw an exception?
I assume Angular 2 treats kendoCellTemplate as an unknown attribute in this case.

Apologies for not communicating this change properly. I've created a "dwarf" issue #205 that we'll update with the full list of renamed directives.

**Comment by dcparsons** [comment]
Thanks, Tsvetomir.

As far as the case sensitivity goes, I think it is correct that the property binding should be case sensitive but I called it out for two reasons:

- In 0.8.2 I bound my grid column to the IsFOO property of my data item, when in fact the property was defined as IsFoo.  The grid handled this oversight and displayed my data without error or any warning (at least nothing was being sent to my console).
- In 0.13.3 IsFOO did not bind to the grid nor did the grid indicate that there was a problem, it just didn't display any data.  

I would expect the grid to emit some sort of error in the event of this invalid binding.

Thanks again!

**Comment by tsvetomir** [comment]
Binding to a field that yields undefined is not an error condition IMO.
Remember, there's no type information available at run-time.

**Comment by dcparsons** [comment]
Hmm.  You are right of course.  I suppose my assumption was predicated on how I would expect binding to work in a more strongly typed environment like .NET.  Closing this issue in favor of [https://github.com/telerik/kendo-angular2/issues/205](205)
