### ISSUE TITLE
DialogComponent and Internationalization

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular2#209]
How to internationalizaize the dialog component?
When the dialog is opened via *ngIf, I see no way how to set title (and others texts) in the component code.
Any suggestions?
Txs

**Comment by KirilNN** [comment]
Have you tried with attribute binding? See [this](http://plnkr.co/edit/llVbQEj4C6oIe0uLLbBm?p=preview)

**Comment by EricSch** [comment]
Thank you, yes. 
Seems to be the only way. Was trying with ViewChild.

**Comment by KirilNN** [comment]
I think that this is the way to do it in Angular context. 

Glad I helped!

**Comment by EricSch** [comment]
would be nice if I could use our i18n directive, but it doesn't work neither:
`        <button kendoButton (click)="onClose(0)" i18n="btn-no"></button>`
