### ISSUE TITLE
Providing custom IntlService to NumericTextBox

### ISSUE THREAD

**Issue by avitiw** [telerik/kendo-angular2#216]
I was trying to create a custom Intl Service and configure it use it in NumericTextBox. Please refer plunker http://plnkr.co/edit/5lEDNSWcQVRFypBXbijI?p=preview .

The service is used when passed to component but the control is not calling it. How can I provide custom formating like for negative numbers show the value in bracket?

**Comment by avitiw** [comment]
On changing the SystemJS to point to npm main.js instead of cdn module, the custom Intl Service is not getting called.

**Comment by ggkrustev** [comment]
Hi @avitiw,
thanks for bringing this up. It seems that the current usage of IntlService internally prevents the ability to define custom implementations. I logged the problem in a separate issue, listing the all affected components:

https://github.com/telerik/kendo-angular2/issues/218

I will close this one in favor of the more `meta`-like issue. Please subscribe to it to be notified when it is closed. I assume that we will fix the problem in no time.
