### ISSUE TITLE
ahead-of-time compilation timeframe

### ISSUE THREAD

**Issue by nickcam** [telerik/kendo-angular2#22]
Hi Guys,

Great work on the beta so far! 
I've just read in this issue #16 - that ahead-of-time compilation is not yet supported.

Is this something that may be supported soon?

Thanks,
Nick

**Comment by rusev** [comment]
Indeed there isn't support for ahead-of-time compilation yet. This is definitely something that will work on. 

However there are changes required in the components source code in order to pass through `ngc`  compiler.

**Comment by nickcam** [comment]
Yeah I'm not surprised, I've just had to refactor a lot of code so ngc can compile it as well.
Thanks.
