### ISSUE TITLE
Support for FormControl directive?

### ISSUE THREAD

**Issue by EricSch** [telerik/kendo-angular2#220]
When I try to use the [FormControl directive](https://angular.io/docs/ts/latest/api/forms/index/FormControlDirective-directive.html) in the multiselect, angular throws an error:
`Can't bind to 'formControl' since it isn't a known property of 'kendo-multiselect'`

Will you support this model binding?

**Comment by rusev** [comment]
This should be working. See the following example cloned from the [Reactive forms](http://www.telerik.com/kendo-angular-ui/components/dropdowns/multiselect/#toc-reactive-forms) section of the documentation.

http://plnkr.co/edit/seGOu2RPMBVE7vsv2jH7?p=preview

**Comment by EricSch** [comment]
We are using it like that, only without the formGroup-directive on the form tag:

`                <kendo-multiselect class="col-md-12"
                                   name="verantwortliche"
                                   [data]="verantwortlicheData"
                                   textField="text"
                                   valueField="id"
                                   [valuePrimitive]="true"
                                   [formControl]="formModel.formGroup.get('verantwortliche')">
                </kendo-multiselect>`

Still throws the error. I will check my code for more differences. 
Thank you

**Comment by EricSch** [comment]
Yes, it works like you mentioned. 
My module export was wrong, had also to re-export angular forms.
