### ISSUE TITLE
Keep "kendo-ui-core" component opensource on angular 2  or build on top @angular/material  or ng-bootstrap 

### ISSUE THREAD

**Issue by badre429** [telerik/kendo-angular2#222]
Please keep "kendo-ui-core" component opensource on angular 2 
(button, card, checkbox, radio, input	, sidenav,  toolbar, list, grid-list, icon, progress-spinner, progress-bar tabs, slide-toggle, button-toggle,  slider... ) 
are already opensource on top of  @angular/material  or ng-bootstrap

**Comment by petyosi** [comment]
Thank you for your feedback @badre429. 

Open sourcing bits of Kendo UI for Angular 2 is not in our immediate plans. Things may change in the future, if we see that this brings value for our customers and aligns with our business goals.
