### ISSUE TITLE
npm ERR! 404 no such package available : @telerik/kendo-inputs-common

### ISSUE THREAD

**Issue by aarmora** [telerik/kendo-angular2#23]
Error happens when attempting to install kendo-angular-inputs.

```
npm ERR! 404 no such package available : @telerik/kendo-inputs-common
npm ERR! 404
npm ERR! 404 '@telerik/kendo-inputs-common' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@progress/kendo-angular-inputs
```'

**Comment by aarmora** [comment]
Looks like this is also happening with dropdowns.

```
npm ERR! 404 no such package available : @telerik/kendo-dropdowns-common
npm ERR! 404
npm ERR! 404 '@telerik/kendo-dropdowns-common' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@progress/kendo-angular-dropdowns'
```

**Comment by aarmora** [comment]
Looks like it's happening with quite a few others. What is available looks great, looking forward to more!

**Comment by KirilNN** [comment]
Looks like the package is available here:

https://www.npmjs.com/package/@telerik/kendo-inputs-common

Which version of the package are you using?

**Comment by tsvetomir** [comment]
Make sure your main registry is npmjs.org:
`npm set registry https://registry.npmjs.org/`

**Comment by aarmora** [comment]
I'm just running `npm install -S @progress/kendo-angular-inputs`. I'm going to update to node 5 now to confirm that's not the problem. I'm currently on 4.4.3.

**Comment by aarmora** [comment]
@tsvetomir It's not, that's exactly the problem. Nice work. I just ran `npm config set "@telerik:registry" http://registry.npmjs.org/` and it is now working like a charm.
