### ISSUE TITLE
Kendo DropDownsModule breaks

### ISSUE THREAD

**Issue by Tenmak** [telerik/kendo-angular2#24]
@underlog  : I've been following the guide "Getting Started" to setup a DropDownList component from the documentation, (and yesterday it did work), but since this morning, I get the following SystemJS XHR Error  :

> zone.js:203 Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:39351/node_modules/@progress/kendo-dropdowns-common/dist/npm/js/bundle.js

Looking a bit more into the error, it seems it's coming from the ComboBox Component : 

> Error loading http://localhost:39351/node_modules/@progress/kendo-dropdowns-common/dist/npm/js/bundle.js as "@telerik/kendo-dropdowns-common/dist/npm/js/bundle" from http://localhost:39351/node_modules/@progress/kendo-angular-dropdowns/dist/npm/js/combobox.component.js

As a matter of facts, the combobox example plunker you provide from your documentation is broken as well : 

Doc link : http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/
Plunker link (didn't edit anything) : http://plnkr.co/edit/NFjHlaiZwJMmo7e2ECel?p=preview

**Comment by gyoshev** [comment]
Thank you for reporting this. The error has been fixed in the latest packages, and on the documentation site. I have answered in the [StackOverflow thread](http://stackoverflow.com/a/39639712/25427), along with the details of why the error has occurred, as well as the required steps for fixing it in your SystemJS configuration.

**Comment by Tenmak** [comment]
So I have this dependency in my package.json, which seems to be the last update : 

             "@progress/kendo-angular-dropdowns": "^0.10.1",

With these mappings in my systemJS.config.js :

            // kendo packages
            '@progress/kendo-angular-dropdowns': 'npm:@progress/kendo-angular-dropdowns',
            '@progress/kendo-angular-popup': 'npm:@progress/kendo-angular-popup',
            '@progress/kendo-popup-common': 'npm:@progress/kendo-popup-common',
            // kendo dependencies
            '@telerik/kendo-dropdowns-common':'npm:@telerik/kendo-dropdowns-common',

            [...]

            '@progress/kendo-angular-dropdowns': {
                main: './dist/npm/js/main.js',
                defaultExtension: 'js'
            },
            '@progress/kendo-angular-popup': {
                main: './dist/npm/js/main.js',
                defaultExtension: 'js'
            },
            '@progress/kendo-popup-common': {
                main: './dist/npm/js/main.js',
                defaultExtension: 'js'
            },
            '@telerik/kendo-dropdowns-common': {
                defaultExtension: 'js',
                main: "./dist/npm/js/main.js"
            },   

- I have deleted the node_modules folder, updated the package.json file, and did `npm install` and I updated the `systemjs.config.js` file as well

- I did serve the packages using gulp and I checked the files where in the `wwwroot/node_modules` folder

=> I still get the following error at start : 

![22-09-2016 15-36-07](https://cloud.githubusercontent.com/assets/19605586/18750177/5b7cb2fa-80da-11e6-9da6-32c8f70c8942.png)

Am I still missing something to make it work ?

**Comment by ggkrustev** [comment]
Could you verify that the correct npm packages are loaded?
```
npm ls @progress/kendo-angular-dropdowns -> v0.10.1
npm ls @progress/kendo-dropdowns-common -> v0.1.1
```
The setup looks OK. If the latest versions of the packages are loaded, the widgets should work (just like our official site now).

**Comment by CalvinDale** [comment]
I'm using a recent Angular-CLI version that uses _Webpack_ rather than _SystemJS_.
```
D:\Cli2> ng -v
angular-cli: 1.0.0-beta.15
node: 6.5.0
os: win32 x64
```
When I ran `npm i --no-optional -S @progress/kendo-angular-dropdowns`, the `dropdowns-common` bits installed with it were the `@telerik` version rather than the `@progress` version.

![image](https://cloud.githubusercontent.com/assets/2473501/18759613/1ad6b2e6-80b2-11e6-8e6b-5e2fa44cfb26.png)

...and it's not working.

**Comment by ggkrustev** [comment]
This still works just fine on our end. Could you post a repo link that demonstrates the issue?

**Comment by underlog** [comment]
Closing this, we need reproducible sample to help further.
