### ISSUE TITLE
Kendo Styling / SCSS

### ISSUE THREAD

**Issue by masaanli** [telerik/kendo-angular2#26]
**On the site there stands:**
_There are several ways to include the Kendo UI theme in your project. We recommend Webpack and its Sass loader, which allows the customization of the Kendo UI theme by using Sass variables._

But how and where do I link them?

I've now for example linked with Webpack (angular cli) to this:
      "styles": [
        "styles/main.scss",
        "../node_modules/@progress/kendo-angular-inputs/dist/npm/css/main.css",
        "../node_modules/@progress/kendo-angular-grid/dist/npm/css/main.css"
      ],

But I want the SCSS files and also the Bootstrap variant, this exists right?
You've the option for the Kendo styling or Bootstrap 4 styling?

So I want SCSS and the Bootstrap 4 Styling, is there somewhere a Guide or something simular howto?

**Comment by jofran73** [comment]
From looking at their plunker samples I think you have to add "@telerik/kendo-theme-bootstrap": "0.5.1" to your packages.json and either use all.css or build your custom css file from the sass-sources. The stylesheet is linked without further magic in the html-file that hosts your angular-app.
I'm not sure this is the way it's intended, though.
Besides that, it seems that at least the ScrollViewComponent is broken using the bootstrap-theme. So I went with the default-theme "@telerik/kendo-theme-default": "1.26.0" until things mature.

**Comment by masaanli** [comment]
@jofran73 Yeah ok, but the idea's is that I can use a scss file.

So if I change the Bootstrap Variables Kendo is automatically changed too..

If I use the css file there are just no benefits...

**Comment by jofran73** [comment]
The node package contains the scss source-files which respect the variables.scss from bootstrap. So to create a custom_kendo_theme_bootstrap.css, create a custom_kendo_theme_bootstrap.scss:
```scss
@import "custom_variables";
@import "../node_modules/bootstrap-sass/assets/stylesheets/bootstrap/variables";
@import "../vendor/@telerik/kendo-theme-bootstrap/src/_kendo.bootstrap.scss";
```
I didn't try anything with it, because my page was broken with the default css already.

**Comment by masaanli** [comment]
When I add a link directly to _kendo.bootstrap.scss or copy the _kendo.bootstrap.scss and fix the path's.

I get on both an error:

`ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles/main.scss                                                                                                                   
Module not found: Error: Can't resolve './../common/font/kendo-glyphs.woff' in 'C:\repos\angular-kendo-test\angular-kendo-test-web\src\styles'                                                                        
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles/main.scss 6:134363-134408                                                                                                         
 @ ./src/styles/main.scss                                                                                                                                                                           
 @ multi styles                                                                                                                                                                                     
Child html-webpa`

I'm using the Angular CLI.

**Comment by masaanli** [comment]
@jofran73 the bootstrap-sass must be bootstrap-4 ;)

**Comment by masaanli** [comment]
Up, opened this 9 days ago and still now valid answer..

SCSS integration is just not working? Must be something important.

**Comment by gyoshev** [comment]
@masaanli thanks for bringing this to our attention. We are currently working on a help topic about styling, but here is the gist. There are quite a few ways to include styles for the components:

1. Use the default theme from the specific component npm package. This works well if you use one component package and do not customize the default theme.
2. Use the built CSS file from the kendo-theme-default / kendo-theme-bootstrap npm packages. This includes the styling for all components, and may grow quite a bit in size. Use this if you plan on using many components without customizing the theme.
3. Add a dependency to one of the theme npm packages. After this, you can build a theme that includes only the components that you need, and customize any variables.

To answer your original question: you can use the third approach, as shown in the [ng2-dashboard app](https://github.com/telerik/ng2-dashboard) ([scss](https://github.com/telerik/ng2-dashboard/blob/master/web/app/app.style.scss), [component](https://github.com/telerik/ng2-dashboard/blob/master/web/app/app.component.ts#L6-L11), [webpack.config](https://github.com/telerik/ng2-dashboard)). This way you can change the bootstrap variables in your scss file, and they will be picked up by both bootstrap and kendo-theme-bootstrap.

**Comment by masaanli** [comment]
@gyoshev That's exsactly what I did right now, but then i get an error because of the font's it could not found...

So i'm searching for a way to disable the fonts or change the path of the fonts..

`'./../common/font/kendo-glyphs.woff'`

**Comment by gyoshev** [comment]
@masaanli The dashboard app does not seem to hit this problem, how does the setup of your app differ from it? Can you provide a reproduction?

**Comment by gyoshev** [comment]
The theme now allows the font icon location to be overridden via the `$icon-font-dir` variable. See [this issue](telerik/kendo-theme-default#41) for more details. For more information about the use of the SCSS theme, see the [topic in the documentation](http://www.telerik.com/kendo-angular-ui/components/styling/).
