### ISSUE TITLE
Using Kendo Switch in Kendo Grid - Switch Animation not working

### ISSUE THREAD

**Issue by PierLucSimard** [telerik/kendo-angular2#28]
**Problem with kendo-switch in Kendo-grid-colum. The switch animation doest not work until u scroll the grid.** 

![grid code](https://cloud.githubusercontent.com/assets/22493500/18906480/b4e376da-8535-11e6-98ec-0c184ed859da.PNG)

import { Component, OnInit, OnDestroy, ViewChild } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';

import {Http, Response} from '@angular/http';
import {Observable} from "rxjs/Observable";
// Statics
import 'rxjs/Rx';
import 'rxjs/add/observable/throw';

// Operators
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/toPromise';

import * as _ from 'lodash';

import { ValidationViewType } from '../_core/enums';
import { VirtuoPageBodyComponent } from '../_core/directives/virtuo-page-body.component';

import { FormsModule } from '@angular/forms';

import {
  GridDataResult,
  PageChangeEvent
} from '@progress/kendo-angular-grid';

@Component({
  templateUrl: "app/modules/employe/employe-detail.component.html"
})

export class EmployeDetailComponent {

  private pageSize: number = 20;
  private skip: number = 0;

  @ViewChild(VirtuoPageBodyComponent) basePage: VirtuoPageBodyComponent;

  private gridView: GridDataResult;
  private data: any[] = [];
  private ddlDataSource: any[] = [];

  user: any = {};

  constructor(
    private router: Router, 
    private http: Http) {

    var count = 1;

    for (var i = 0; i < 5000; i++) {

      var item: any = {
        "Id": 1,
        "ProductName": "Aniseed Syrup",
        "UnitPrice": 10.0000,
        "Discontinued": false,
        "Category": {
          "CategoryID": 2,
          "CategoryName": "Condiments",
          "Description": "Sweet and savory sauces, relishes, spreads, and seasonings"
        }
      }

      item.Id = i;
      item.isAutorise = false;

      this.data.push(item)
    }

    this.loadProducts();

    this.getData();

    this.ddlDataSource = [
      { Id: 1, Display: "2016/9/28 - 2016/10/14" },
      { Id: 2, Display: "2016/10/14 - 2016/10/31" },
      { Id: 3, Display: "2016/11/01 - 2016/11/14" },
      { Id: 4, Display: "2016/11/28 - 2016/12/14" },
      { Id: 5, Display: "2016/9/28 - 2016/10/14" },
      { Id: 6, Display: "2016/10/14 - 2016/10/31" },
      { Id: 7, Display: "2016/11/01 - 2016/11/14" },
      { Id: 8, Display: "2016/11/28 - 2016/12/14" },
      { Id: 9, Display: "2016/9/28 - 2016/10/14" },
      { Id: 10, Display: "2016/10/14 - 2016/10/31" },
      { Id: 11, Display: "2016/11/01 - 2016/11/14" },
      { Id: 12, Display: "2016/11/28 - 2016/12/14" },
      { Id: 13, Display: "2016/9/28 - 2016/10/14" },
      { Id: 14, Display: "2016/10/14 - 2016/10/31" },
      { Id: 15, Display: "2016/11/01 - 2016/11/14" },
      { Id: 16, Display: "2016/11/28 - 2016/12/14" }];
  }

  getData (): any {
    // return this.http.get("http://localhost:56872/api/test/mockups/1")
    //               .map(response => response.json())
    //              .subscribe(data  => {
    //                 var test = data;
    //              });
}

  onKey(event: any) {
    this.user.name = event.target.value;
  }

  // Commands

  executeEdit(item) {

  }

  executeDelete(item) {
    this.gridView.data = _.filter(this.gridView.data, function (product) {
      return product.Id !== item.Id;
    });
  }

  protected pageChange(event: PageChangeEvent): void {
    this.skip = event.skip;
    this.loadProducts();
  }

  private loadProducts(): void {
    this.gridView = {
      data: this.data.slice(this.skip, this.skip + this.pageSize),
      total: this.data.length
    };
  }

  executeSave() {
    this.bind();
  }

  canExecuteSave() {
    return true;
  }

  bind() {

    var validationItems: Array<any> = [
      { description: "Nom requis", type: ValidationViewType.Error },
      { description: "Age requis", type: ValidationViewType.Error },
      { description: "Description requise", type: ValidationViewType.Warning }
    ];

    this.basePage.load(validationItems);
  }

  executeReturnList() {
    this.router.navigate(['/usager']);
  }
}

![bug switch grid](https://cloud.githubusercontent.com/assets/22493500/18906266/d172629e-8534-11e6-9f66-5afeaede1920.PNG)

**Comment by rusev** [comment]
A runnable demo will be of a great help in order to assist. All seems to be working in the following demo - http://plnkr.co/edit/U9WcIkwdw6hgaI8Wv0tG?p=preview.

**Comment by PierLucSimard** [comment]
After more testing in my project the problem seem to be related also (just like the DDL problem) to using the grid inside a tab control with:

<div *ngIf="active">
    <ng-content></ng-content>
</div>

**Comment by PierLucSimard** [comment]
I was able to do a workaround by fetching the data in the ngAfterViewInit() method....

**Comment by maximedupre** [comment]
I confirm that the Switch doesn't work in a tab control.

**Comment by PierLucSimard** [comment]
I manage to make switch work by modifying my tab control like in the example below... 

http://plnkr.co/edit/DrAntoAtp9AtNJT2cYvL?p=preview



At first I tried to create the tab control using this article (seem to partially work only):
http://blog.thoughtram.io/angular/2015/04/09/developing-a-tabs-component-in-angular-2.html
