### ISSUE TITLE
Dropdowns Initial Release

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-angular2#3]
The DropDown Component Family includes a DropDownList, ComboBox, AutoComplete, and MultiSelect. I guess that we can cover the ComboBox and the DropDownList, initially.

**Comment by tapopov** [comment]
After discussing it for a while, @ggkrustev, @valchev and I prepared basic DropDowns [specification](https://gist.github.com/tapopov/f585a5f9b557e6734faaaabd7c08bffd)

**Comment by valchev** [comment]
Do we really need `readonly` option?

The component does not render HTML `select` element.
The current (KendoUI 1) `readonly` behaviour of "disable but submit" does not seem to be a valid scenario. Am I missing something?

**Comment by ggkrustev** [comment]
I agree that `readonly` support is a bit vague in Angular2. Nevertheless, before ditch the functionality, we will need to see how the Angular Forms works.

The questions that raise in my mind are:
- Does form binding skips 'disabled' inputs?
- If 'disabled' elements are skipped, then does `readonly` is supported?

Basically, we will need to research what is supported and what is not by the new Angular Forms. The investigation will provide pretty solid answers whether to support `readonly`, `disabled` and etc.

**Comment by ggkrustev** [comment]
Here is a short list ofsimilar Angular2 Drop-down components:
- [PrimeNG](http://www.primefaces.org/primeng/#/dropdown)
- [ng2-select](https://valor-software.com/ng2-select/)
- [ng2-dropdown](https://github.com/pleerock/ng2-dropdown)
- [angular-2-autocomplete](http://www.angulartypescript.com/angular-2-autocomplete/)

(fill free to add new if found)

**Comment by ggkrustev** [comment]
### Some thoughts on [(ngModel)] support

#### Binding to objects
It seems that all mentioned components actually work only with objects (return the item at the selected index in the data list).

#### Binding to primitive value 
Will work if the data list contains only primitive values (e.g. list of strings)

#### Binding to primitive value using list of objects
In this case we will need some kind of configuration, either the notorious `valuePrimitive` or a new property binding, though I am not sure how this could even be possible with `ngModel`. We will need to decide whether we should support the 3rd case.

Anyone with an opinion is welcomed to chime in!

**Comment by underlog** [comment]
Suggestion: pick use cases for each case. Challenge them - do they make sense? In my mind, the third option is more or less a heritage from the days when the dropdowns were supposed to model their behavior after the HTML select element.

**Comment by valchev** [comment]
A follow up from an offline discussion with @ggkrustev and @tapopov 

Currently the components support `[value]=“{ object }"` even if `[valuePrimitive]=“true”`. In other words we are able to resolve and display initially provided value of any type, no matter of the `valuePrimitive` configuration option. The `valuePrimitive` has effect only on the output that the component will return when the value is changed.

The fact that one is able to pass primitive value, but might receive object value may be confusing to some developers.

Should we keep the current behaviour or be more restrictive? A possible solution is to throw error when invalid configuration is detected.

**Comment by ggkrustev** [comment]
I would vote to be more restrictive. Although it is 'nice' to have `[value]=“{ object }"` working, it will be quite confusing. We can always loose the validation if a valid scenario is pointed out.

[tl;dr]
In my perspective, when `[valuePrimitive]="true"` is explicitly set by the developer, it is strange to find out that passing an object to the value property binding is actually accepted. In most cases, that value will come from the model (component context) and will be updated back in the `valueChange` callback. It doesn't make any sense to start with object type and then continue with primitive value (change event will pass only the primitive value).

The same scenario is valid for `ngModel` and `formControlName` bindings.

It would be much better to avoid a 'unexpected' behavior, although it looks harmless in the beginning.

**Comment by tsvetomir** [comment]
Don't forget to throw an exception in dev mode if inconsistent configuration is detected.

**Comment by ggkrustev** [comment]
Yeah, definitely. I think that @valchev and @tapopov are already doing that.

**Comment by underlog** [comment]
Initial release is live - http://www.telerik.com/kendo-angular-ui/components/dropdowns/

**Comment by djarekg** [comment]
Is there a time frame for when the other drop down widgets will be available? Ie multiselect

**Comment by underlog** [comment]
Hi,

we will publish our roadmap for the next cycle soon - it will follow the current format.
