### ISSUE TITLE
Require @angular packages as peer dependency

### ISSUE THREAD

**Issue by ggkrustev** [telerik/kendo-angular2#30]
### Description
Currently, Kendo UI components for Angular 2 requires Angular modules as `dependencies` with strict version, e.g.
```
"dependencies": {
    "@angular/core": "2.0.0",
    "@angular/common": "2.0.0",
...
```

Those packages should be peer dependencies:
```
"peerDependencies": {
    "@angular/core": "~2.0.0",
    "@angular/common": "~2.0.0"
 },
 devDependencies: {
   //move here other @angular packages that are needed only for development
   "zone.js": "",
   "core-js": "",
   ...
 }
```

**important**: use [kendo-angular-tasks@4.0.2 or newer](https://github.com/telerik/kendo-angular-tasks/releases/tag/v4.0.2)

**important**: use [kendo-common-tasks@2.9.10 or newer](https://github.com/telerik/kendo-common-tasks/releases/tag/v2.9.10)

**Comment by ggkrustev** [comment]
List of packages to update:

- [ ] @progress/kendo-angular-buttons
- [ ] @progress/kendo-angular-charts
- [ ] @progress/kendo-angular-dialog
- [ ] @progress/kendo-angular-dropdowns
- [ ] @progress/kendo-angular-grid
- [ ] @progress/kendo-angular-inputs
- [ ] @progress/kendo-angular-intl
- [ ] @progress/kendo-angular-layout
- [ ] @progress/kendo-angular-popup
- [ ] @progress/kendo-angular-scrollview
- [ ] @progress/kendo-angular-sortable
- [ ] @progress/kendo-angular-upload
- [ ] @progress/kendo-charts
- [ ] @progress/kendo-drawing

**Comment by tsvetomir** [comment]
Shouldn't we jump ship and use "^2.0.0" in order to pick up minor versions as well? Let's re-consider this after 2.1 ships out.
