### ISSUE TITLE
Kendo DropDownList - Slow opening

### ISSUE THREAD

**Issue by PierLucSimard** [telerik/kendo-angular2#31]
If u compare with previous kendo component:
http://demos.telerik.com/kendo-ui/dropdownlist/virtualization

DropDownList opening animation could be faster and more fluid.

**Comment by ggkrustev** [comment]
The Angular 2 strives to be a framework and as such has built-in animations support, which we use in our components. The duration that we are using to animate the `popup` component is .2s
```
animate('0.2s ease-in', style({ transform: 'translateY(0)' }))
```
which is exactly the same duration that we are using in Kendo UI Popup for jQuery
```
duration: 200 //milliseconds
```
https://github.com/telerik/kendo-ui-core/blob/master/src/kendo.popup.js#L167

We could consider in future to reduce the duration in Kendo UI Popup for Angular 2, but for now we will keep the same numbers on both sides.

As a side note, I do believe that the Angular Core team are working on improving the animations support and most probably they will work much better in future. We do not have control over the animations performance.

I will close this thread for now, as it does not discusses a bug or feature request.
