### ISSUE TITLE
Tabstrip should use ng-if instead of opacity to show tab content

### ISSUE THREAD

**Issue by PierLucSimard** [telerik/kendo-angular2#32]
Is it possible to use ng-if instead of opacity to show tabstrip content. For heavy UI it will be slow with the current approach. This is an exemple from angular material (1 and 2). They both use ng-if to trigger tab content.

![image](https://cloud.githubusercontent.com/assets/22493500/18908788/0ef57d36-853f-11e6-8c0f-beaed0e49eaa.png)
![image](https://cloud.githubusercontent.com/assets/22493500/18908972/c5b33e32-853f-11e6-876b-534d3b76558f.png)

**Comment by KirilNN** [comment]
Hi @PierLucSimard,

We decided to go with the current implementation having remote content loading in mind, and the fact that a request to the server will be made in case you have remote content. However the approach with `on-demand` rendering is something that we will consider although it will require some breaking changes in the way components are used - introducing templates inside the tabs, so the content is initialized when needed. 

We will explore these options and will keep you updated soon!

**Comment by KirilNN** [comment]
I am happy to say that we have implemented this feature as requested and it is available with the `0.14.0` version. Note that a breaking change was introduced on how the tab content should be structured - you can check the documentation for a runnable example.

**Comment by maximedupre** [comment]
@KirilNN Why did you abandon "We decided to go with the current implementation having remote content loading in mind, and the fact that a request to the server will be made in case you have remote content."? Things are painful now.

**Comment by KirilNN** [comment]
Due to popular demand, we decided to switch the rendering mode. As for the remote content loading - you can implement caching mechanism in order to work it around.

**Comment by maximedupre** [comment]
Remote content loading isn't the only thing to consider. Other heavy tasks like canvas rendering can cause the page to be in an "incomplete state" every time you change tab. That's too bad.

**Comment by KirilNN** [comment]
@maximedupre - we will think of a general caching solution that will work in most cases. So please stay tuned.

**Comment by KirilNN** [comment]
you can track this issue here https://github.com/telerik/kendo-angular2/issues/198

**Comment by maximedupre** [comment]
Oh perfect! I will be watching this issue. Thanks.
