### ISSUE TITLE
How to access the index in the Sortable data loop?

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular2#36]
<kendo-sortable [data]="data">
        <template let-item="item" let-i="i">
            <span>{{ i }}</span>
        </template>
    </kendo-sortable>

This would render a span with nothing in it. I also tried `let-i="index"` with no success.

How can I access the index?

Thanks.

**Comment by maximedupre** [comment]
Not sure, but I think `[ngOutletContext]=\"{item: item, index: index}\"` would do the job.

**Comment by Xizario** [comment]
@maximedupre , thank you for your suggestion.
We also think of passing additional information such as  if the item is Disabled or Active(currently dragged) to the context.

Until this is done, you may enumerate the items manually, something like:
```
<template let-item="item" let-i="index" >
{{i}}
<span>
   {{item}}
</span>
</template>
```

```
class AppComponent {
  private _index: number = 0;
  public index(): number {
    return this._index++;
  }
}
```

**Comment by maximedupre** [comment]
I tried your suggestion, but it doesn't seem to work. `{{ i }}` does not output a value.

**Comment by maximedupre** [comment]
@Xizario Your example assumes that the template you posted is the template of `AppComponent`, right?

**Comment by Xizario** [comment]
@maximedupre, you are correct, the example above would not work. It only worked on my machine, since I was already added the index in the context. 

We will upload a new package soon, and the index will be available for use.
