### ISSUE TITLE
No clear event on kendo-upload

### ISSUE THREAD

**Issue by jvanderbiest** [telerik/kendo-angular2#39]
There is a [remove event](http://www.telerik.com/kendo-angular-ui/components/upload/api/RemoveEvent/) in the upload control that fires when clicking on an individual file (1). Is it possible to execute this event when clicking on "Clear" button (2) or triggering a clear event because I would also like to know if the files are removed using that button.

Also a workaround how to add an event on that button would be appreciated :-)

![image](https://cloud.githubusercontent.com/assets/3985995/19112548/bec49578-8b05-11e6-989f-a977b4b5331b.png)

**Comment by Raisolution** [comment]
Hi @jvanderbiest,

Thanks for your input. This is a good idea and we will log it for development.

**Comment by jamesradenz** [comment]
Has the Clear Event been implemented yet? Or is there any workaround to bind a function to the Clear button's onclick?
