### ISSUE TITLE
Inputs Preview Release

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-angular2#4]
The inputs package includes the Switch, Slider, NumericTextBox, MaskedTextBox and ColorPicker components. The initial preview release may be limited to the Switch and the Slider.

**Comment by maroebuck** [comment]
Can we have a must of a keyup event please?

**Comment by underlog** [comment]
Slider and Switch are live - http://www.telerik.com/kendo-angular-ui/components/inputs/
