### ISSUE TITLE
Kendo Grid pageSize property broken

### ISSUE THREAD

**Issue by boutrosc** [telerik/kendo-angular2#40]
It appears that the pageSize property of the kendo-grid is broken. Page size value changes from the UI are not reflected being reflected in the bound component variable. 

This can be tested in the sandbox environment provided here: http://www.telerik.com/kendo-angular-ui/components/grid/#paging.

![pagesize](https://cloud.githubusercontent.com/assets/5430009/19122684/3672a426-8af1-11e6-9eb5-e091c0e265cf.PNG)

**Comment by rkonstantinov** [comment]
The example is incomplete and it will be updated soon. Please refer to this SO thread which describes correct setup http://stackoverflow.com/questions/39779166/telerik-kendoui-angular2-grid-page-size-drop-down-not-updating-displayed-record/39785440#39785440
