### ISSUE TITLE
Kendo UI For Angular 2 (nativescript renderer) [Question]

### ISSUE THREAD

**Issue by jvitor83** [telerik/kendo-angular2#41]
> As i can tell, this components library is for the web platform (Browser Renderer / HTML).

Is there any plan to release **Kendo UI For Angular 2 with Nativescript** or should i call **Kendo UI For Nativescript** or even **Kendo UI For Angular Native**?

**Comment by valentinstoychev** [comment]
What is the scenario you want to enable?

**Comment by jvitor83** [comment]
> _It is just a question to see if Telerik has any plans on that._

But, a scenario would be something like using the grid, or others components at the app!
Something like:
```typescript
<kendo-grid [data]="gridData"></kendo-grid>
```
who can be used the same way in both renderers.

Got that when i see the [https://www.nativescript.org/blog/angular-2-web-and-mobile-demo-app-using-kendo-ui-and-nativescript](https://www.nativescript.org/blog/angular-2-web-and-mobile-demo-app-using-kendo-ui-and-nativescript) and look at the source code [https://github.com/telerik/ng2-dashboard](https://github.com/telerik/ng2-dashboard)

> Have seen that the components at mobile don't have any kendoui component.
So, i come to ask.

**Comment by petyosi** [comment]
Hi @jvitor83 ,

Thank you for the interest! Up to your question, we don't plan on introducing a grid that can be rendered in both contexts. Mobile UI is tricky business in general, and we don't believe that an semi-automated conversion of Web UI to Mobile one yields effective results (apart from looking impressive in staged demos). With that in mind, we are looking into providing Native Mobile components in Kendo UI, with the implementation strategy visible in the ng2-dashboard repository, where services and styling are shared between the two contexts. 

Further details of our plans are available in [our Roadmap](http://www.telerik.com/kendo-angular-ui/roadmap/)—we published it recently, so my guess is that it may be new to you.
