### ISSUE TITLE
Kendo for Angular 2: Grid styling using headerClass, class or footerClass do not work

### ISSUE THREAD

**Issue by shanegela** [telerik/kendo-angular2#42]
Kendo for Angular 2: Grid styling using headerClass, class or footerClass do not work.
The documentation example for Styling uses headerStyle, style, footerStyle and seems to work.
http://www.telerik.com/kendo-angular-ui/components/grid/

But if I switch the example to use headerClass, class, or footerClass, the styles do not apply.
![kendo1](https://cloud.githubusercontent.com/assets/10292625/19202785/da49a278-8c88-11e6-891e-3a63dee9839b.jpg)

See plunker example: http://plnkr.co/edit/Vy8ztuercRsR4ESXbCPU?p=preview

![kendo2](https://cloud.githubusercontent.com/assets/10292625/19202783/d85c7cba-8c88-11e6-83bc-fc4d13fab1af.jpg)

**Comment by rkonstantinov** [comment]
The headerClass is not applied due to few configuration errors in the sample:

 - as the class name is a string it should be enclosed in quotes

 - the component styles should be defined via the style**s**(plural) property. In the sample the style(singular) is used instead.

- the appropriate encapsulation should be set to the parent component.

```javascript
@Component({
    selector: 'my-app',
    styles: ['/*..*/'],
    encapsulation: ViewEncapsulation.None,
    template: `	
        <kendo-grid [data]="gridData">
            <kendo-grid-column
                 field="ProductName"
                 [headerClass]="'test'">
            </kendo-grid-column>
        </kendo-grid>
    `
})
```

**Comment by shanegela** [comment]
I made the updates you listed to the plunker example, but the styles are still not being applied.

![kendo3](https://cloud.githubusercontent.com/assets/10292625/19241185/3942c4ea-8ec2-11e6-9d4f-85f64ae4bd8e.jpg)

**Comment by rkonstantinov** [comment]
You should increase the specificity of the CSS selector you are using in order to override the existing styling. For example adding an `!important` just for the test.

**Comment by shanegela** [comment]
I added important to test but still do not see the styling.  When I run the debugger on plunker I don't even see the test styles in the stack of styles to apply.
http://plnkr.co/edit/Vy8ztuercRsR4ESXbCPU?p=preview

![kendo4](https://cloud.githubusercontent.com/assets/10292625/19242218/1fc3652e-8ec7-11e6-8039-e92a4f38b220.jpg)

**Comment by petyosi** [comment]
Plunkr you have posted works for me, unless I am missing something. 
![screen shot 2016-10-10 at 7 03 59 pm](https://cloud.githubusercontent.com/assets/13347/19242551/5c5f6fd2-8f1c-11e6-9dec-940a46d1dd77.png)

**Comment by shanegela** [comment]
You're right. I had to stop and rerun plunker and now it does work.
Thank you all for your help.

**Comment by pravinsawant** [comment]
Thank you so much already i sent too much time to workout this. You saved my further time. Thanks buddy.
