### ISSUE TITLE
Kendo Grid Filter Row?

### ISSUE THREAD

**Issue by masaanli** [telerik/kendo-angular2#43]
When can we expect a Kendo Grid Filter Row. Now the Grid does not contain's a filetering possibility.

**Comment by petyosi** [comment]
We don't have a concrete timeline for the grid filtering feature. There are a number of prerequisites of this feature, the most significant one being the date pickers. You can review our roadmap for further details - http://www.telerik.com/kendo-angular-ui/roadmap/

**Comment by masaanli** [comment]
Is there a way we can add a row below the first columns ourselves?

So I can make it myself?

**Comment by ssmartin** [comment]
Any updates on this issue? Will you provide this in May at the final release?

**Comment by petyosi** [comment]
@ssmartin @masaanli the grid filtering is part of the must-haves - we are going to work on this for our next iteration: http://www.telerik.com/kendo-angular-ui/roadmap/
