### ISSUE TITLE
jQuery rowTemplate equivalent for GridComponent

### ISSUE THREAD

**Issue by martinopic** [telerik/kendo-angular2#44]
Hi,

first of all great work guys! Very excited about KendoUI coming to angular2.

Is an equivalent of Grid jQuery rowTemplate available? Current AngularUI GridComponent seems limited with respect to jQuery but having at least "basic" API hooks would allow to sidestep many current limitations. If there isn't I hope there will soon be as it's really limiting on what can you render (and it's actually blocking us from further use).

Thanks

P.S.

I've found another (unanswered) "request" for this skimming through Stackoverflow KendoUI Angular2 questions:

http://stackoverflow.com/questions/39735422/kendo-ui-angular-2-rowtemplate

**Comment by rkonstantinov** [comment]
Hi and thanks for the suggestion.
Could you please give us a bit more information about what you are trying to achieve using the row template. Maybe we could suggest a way to implement it with the current feature set.

**Comment by martinopic** [comment]
Hi,

my specific case is basically showing a list of articles per country so it's essentially grouping but also I need to show a specific header for each "group" title showing more information for the country that those found in the grid data.

suppose I have

```
countries = [
{ name: Italy, invoices: 23, customers: ... },
{ name: Spain, invoices: 34, customers: ...},
...
]
```

And thise articles (which constitutes the data for the grid):

```
articles = [
{ name: "article1", country: "it"}
{ name: "article2", country: "it"},
{name: "article3", country: "es"},
...
]
```

Now the grid will show the article ordered by country but before each country change (group) for the article the grid will show a special row (with special formatting, colspan etc.) with all the information about the country and more related information.

Don't know if this would be possible with grouping but as it's also lacking from GridComponent I think we could get away with rowTemplate which certainly would be useful in tons of other cases.

Thanks for your help.

**Comment by rkonstantinov** [comment]
This sounds more like a grouping functionality (which is not currently available) or maybe using the DetailTemplate instead. Maybe I'm missing something, but did you have this implemented with the current Kendo Grid for jQuery rowTemplate feature?

**Comment by martinopic** [comment]
No I have no current implementation of this with KendoUI, we are trying to swtich an application to KendoUI Angular2 but currently the app is not using KendoUI and yes, I suspect too this would be a charm with grouping functionality but in my case this can also be handled simply ordering and aggregating the data before giving them to the grid and having the possibility to programmatically render a row (which is rowTemplate as far as I understand) which is a fundamental feature for a grid anyway.

**Comment by rkonstantinov** [comment]
OK I see. What I think will not fit with the rowTemplate approach is that it seems you are trying to render multiple row elements which to be associated with a single data item. This I'm afraid will not be possible.

Either way the RowTemplate is definitely a thing which we will try to add at some point before going out of the BETA.

**Comment by martinopic** [comment]
It seemed to me that it would be possible to render multiple rows associated with a single data item with row template. At least by looking at jQuery KendoUI documentation it seems you can render the entire row (``` <tr> ... </tr>```) so why not rendering two rows instead (```<tr>... </tr><tr>...</tr>```). Or you think my case could be handled just by grouping functionalities?

Any estimate date for any of this solutions? 

Thanks a lot.

**Comment by rkonstantinov** [comment]
Indeed, as far as rendering goes, it is possible to render multiple elements. However there are other features of the Kendo UI for jQuery Grid that assumes that the row element count matches the number of records. Thus, such scenarios are not supported.

Although, it is ahead of us to decide the exact implementation of RowTemplate feature with Ng2 GridComponent, I guess that this limitation will still apply.

You should keep an eye on [our roadmap](http://www.telerik.com/kendo-angular-ui/roadmap/).

**Comment by martinopic** [comment]
I'll just keep an eye on progresses. It wouldn't be bad if one could mark a row as "decoration" and avoid this strict requierements of rows/items matching.

Thanks for your prompt answers and keep up the good work! :-)
