### ISSUE TITLE
Keyboard navigation and RTL support in grid control

### ISSUE THREAD

**Issue by wz9** [telerik/kendo-angular2#46]
Hi,

JQuery version of Kendo grid has a “Navigatable” flag that is used to enable keyboard navigation. It seems the current version of NG2 grid control doesn't support the flag. Do you have a timeline when this will be added? It's a high priority request as part of accessibility support. 

Also needed is proper RTL language support. In current implementation the grid header and content are misaligned under RTL.

Thanks.

**Comment by HJoost** [comment]
Hi,

yes the keyboard navigation is a must have also for us!

**Comment by rusev** [comment]
Hello guys,

Keyboard navigation will be implemented at some point. Meantime you can forward your request to the [UserVoice](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback).
