### ISSUE TITLE
Panelbar not working when Panelbar Items are used by *ngFor in a separate component.

### ISSUE THREAD

**Issue by whizkidwwe1217** [telerik/kendo-angular2#50]
I created a component that uses a panel bar and another separate component that uses the panel bar item as a template. Then when I put it inside the panel bar directive, it did not work.
**Component 1 (Header)**
`<kendo-panelbar>
	<wafe-panel-sidebar-item [pages]="pages">
	</wafe-panel-sidebar-item>
</kendo-panelbar>
`
**Component 2 (Details)**
`<kendo-panelbar-item *ngFor='let page of pages' title='{{page.name}}'>
</kendo-panelbar-item>`

**Comment by rusev** [comment]
Can you provide a reproduction of the problem?
