### ISSUE TITLE
Examples in Plunkr

### ISSUE THREAD

**Issue by HJoost** [telerik/kendo-angular2#51]
Hi,

the plunker examples from http://www.telerik.com/kendo-angular-ui/components/ don't work anymore. For example:

http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/#

Console:

www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-angular-popup/:1 GET http://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-angular-popup/ 

XMLHttpRequest cannot load http://www.telerik.com/kendo-angular-ui/npm/node_modules/@progress/kendo-angular-popup/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access. The response had HTTP status code 404.

**Comment by tsvetomir** [comment]
Thanks for reporting this issue. The kendo-angular-dropdowns are missing a dependency that prevents them from running in plnkr. You can add the following in the packages section of `systemjs.config.js`:

```
      '@progress/kendo-angular-popup': {
          defaultExtension: 'js',
          main: "./dist/npm/js/main.js"
      },
```

See this [updated plunkr](http://plnkr.co/edit/EGDryLkMCpPBNX7xxDIZ?p=preview) for an example.

We'll fix this issue in the next upload.

cc @tapopov @valchev @gyoshev

**Comment by tsvetomir** [comment]
Fixed on the live site as well.
