### ISSUE TITLE
Disable Combobox error: "Cannot read property 'isFirstChange' of undefined"

### ISSUE THREAD

**Issue by HJoost** [telerik/kendo-angular2#52]
Hi,

i tried to disable a combobox, but there is a error appearing in the console:

http://plnkr.co/edit/NXnGORSW7LaImNMHA6By?p=preview

**Comment by tapopov** [comment]
The issue originates from an [if statement](https://github.com/telerik/kendo-angular-dropdowns/blob/master/src/combobox.component.ts#L376) that lacks a null check. This `if` statement is already removed in a feature branch that is soon to be merged to master.

**Comment by tapopov** [comment]
Fixed in v0.12.0
