### ISSUE TITLE
Question: Any plans for RadDocking and PivotGrid controls?

### ISSUE THREAD

**Issue by sanket360** [telerik/kendo-angular2#55]
I am looking for couple of controls in future from kendo-angular2 compoents library

1. RadDocking control (http://docs.telerik.com/devtools/silverlight/controls/raddocking/overview2)

2. PivotGrid with xmla support (http://docs.telerik.com/devtools/silverlight/controls/radpivotgrid/overview)

Please let me know if you have any plans for these controls.

**Comment by petyosi** [comment]
Hi, 

we don't have concrete plans for porting these components. You can take advantage of our [newly opened feedback portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback) and post your ideas there.
