### ISSUE TITLE
How to implement drag and drop between 2 grids.

### ISSUE THREAD

**Issue by randyangeles** [telerik/kendo-angular2#56]
Hi,

Haven't received any answers on my StackOverflow question so I figured I'll post here.
(link to question: http://stackoverflow.com/questions/39986756/kendo-ui-angular2-how-to-implement-drag-and-drop-between-2-grids)

I haven't found any information in the docs on how to implement drag and drop between 2 grids. Haven't seem any mention of it in the roadmap too.

Can anyone suggest an approach for this?

Thanks!

**Comment by dimodi** [comment]
Hello @randyangeles,

Thank you for your interest in Kendo UI for Angular 2.

This GitHub Issues list is for bug reports only, so I am going to close this issue with this comment.

On a side note, drag and drop between Grids is currently not available as a built-in feature.

Kendo UI for Angular 2 is currently in beta stage and free for use and community preview. We will release a commercial offering in 2017 and that will also include dedicated support service.

In the meantime, the [Community &amp; Support](http://www.telerik.com/kendo-angular-ui/support/) page outlines the available options to receive technical assistance via [StackOverflow](http://stackoverflow.com/questions/tagged/kendo-ui-angular2) or [Telerik Professional Services](http://www.telerik.com/professional-services), or report issues in our [kendo-angular2 GitHub repository](https://github.com/telerik/kendo-angular2/), or submit feature requests in our [UserVoice portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback).

Stay tuned and keep an eye on our [Kendo UI for Angular 2](http://www.telerik.com/kendo-angular-ui/) site and the [roadmap](http://www.telerik.com/kendo-angular-ui/roadmap/), the [Telerik blogs](http://www.telerik.com/blogs) (specifically, the [Kendo UI Product Manager posts](http://www.telerik.com/blogs/author/petyo-ivanov)) and GitHub repository for updates.

**Comment by randyangeles** [comment]
Alright, thanks for the response  @dimodi.

**Comment by TUSHARDM** [comment]
https://docs.telerik.com/kendo-ui/knowledge-base/drag-and-drop-rows-between-two-grids
Is this supported now in Angular 2+,
I can only find similar example at :
https://angular-d3jkhn-puzqqv.stackblitz.io
