### ISSUE TITLE
Add a drag handle option for the Sortable

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular2#57]
Every drag and drop library I have used in the past support a handle option, meaning that the drag of an item only occurs if the the user has clicked on a specific child element of the item. Normally this option's value is a selector.

    <kendo-sortable [data]="tracksData" [handle]="#headerBar">
        <template let-trackData="item">
            <track [tempo]="trackData.tempo"></track>
        </template>
    </kendo-sortable>

Where `#headerBar` is the selector of an indirect or direct child element of `TrackComponent`.

I don't see how this can be achieved with the current API, but perhaps I'm wrong.

Here are 2 examples of an API for a `handle` option:
- [jQuery UI](http://api.jqueryui.com/draggable/#option-handle)
- [dragula](https://github.com/bevacqua/dragula#optionsmoves)

**Comment by petyosi** [comment]
This sounds like a cool feature suggestion. You can add that to our [feedback portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback), and we will consider it for our future releases.

**Comment by maximedupre** [comment]
@petyosi Sure!

**Comment by maximedupre** [comment]
Has the feedback portal disappear?

**Comment by petyosi** [comment]
we are facing temporary outage, will restore it.

**Comment by FlamingCeo** [comment]
Any update on this yet? I have been looking for the drag handler  as well

**Comment by maximedupre** [comment]
Related feature request: https://feedback.telerik.com/kendo-angular-ui/1360537-add-a-drag-handle-option-for-the-sortable

**Comment by ZhipengZeng** [comment]
any updates on this feature request?
