### ISSUE TITLE
npm install -S @progress/kendo-angular-grid doesn't work (Access is denied) 

### ISSUE THREAD

**Issue by anj01** [telerik/kendo-angular2#58]
Hi,

I 'm trying to get the Grid component, but I 'm getting always  error. I'm logged in to scope @progress and @telerik.  Other compenents (button, input) have worked well. Something seems to be wrong . Please help me.

Thanks in advance

![image](https://cloud.githubusercontent.com/assets/22910183/19475154/ede3fad8-9532-11e6-89ec-e74bb006fa71.png)

**Comment by eeasss** [comment]
Hi anj1, we need your email address in order to check the logs what went wrong. If you would rather not leave it in this thread you can fire us a product feedback ticket in the support system. http://www.telerik.com/account/

**Comment by gyoshev** [comment]
@anj01 while it may not solve the problem, you should also update npm to v3, as it is a [prerequisite for Angular 2](https://angular.io/docs/ts/latest/quickstart.html) (and Kendo UI for Angular 2)

**Comment by anj01** [comment]
@gyoshev thanks for update hint! I' have updated to latest npm version, but always the same error.

generated log by npm:
[npm-debug.log.txt](https://github.com/telerik/kendo-angular2/files/541209/npm-debug.log.txt)

**Comment by gyoshev** [comment]
@anj01 the log shows that the permission error is triggered when the `@telerik/kendo-intl` package is fetched from the private registry. [The @telerik packages are public](https://www.npmjs.com/~telerik) and don't need to go through the private NPM registry. Please check the NPM configuration on your machine -- it should not be used for @telerik packages. The configuration can be found in `~/.npmrc`, and an offending line is likely to be  `@telerik:registry=https://registry.npm.telerik.com/`.

**Comment by anj01** [comment]
Thanks for answer! I installed node.js v6.x because I used v4.x before and now it works! 

Have a nice evening!
