### ISSUE TITLE
Prevent unselect a selected row - Grid

### ISSUE THREAD

**Issue by archs147** [telerik/kendo-angular2#61]
Hi

Is it possible to prevent unselect a selected row. How can I keep the row selected when I clic on the row selected?.

Ricardo

**Comment by rusev** [comment]
Current implementation doesn't allow this. You can add that to our [feedback portal](http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback), and we will consider it for our future releases.
