### ISSUE TITLE
Angular 2 charts

### ISSUE THREAD

**Issue by joedayz** [telerik/kendo-angular2#62]
I am following the demo in http://www.telerik.com/kendo-angular-ui/components/charts/chart/#structural-directives , configure my Systemjs.config.js but I am getting this error:

node_modules/@progress/kendo-drawing/dist/npm/js/drawing.d.ts(11,5): error TS7010: 'then', which lacks return-type annotation, implicitly has an 'any' return type.
node_modules/@progress/kendo-drawing/dist/npm/js/drawing.d.ts(12,5): error TS7010: 'catch', which lacks return-type annotation, implicitly has an 'any' return type.

**Comment by MKPMani** [comment]
Hi, can you pls let me know which version you work? I tried 0.5.3 even cant load the ChartModule in my component page. throw error as "Chroma-js" not find

**Comment by KirilNN** [comment]
Hi @joedayz,

Thanks for reporting this!

The problem comes from the latest Typescript version 2.0.3 and it should be fine with an older version. Anyway - It will be fixed with the next version of the kendo-angular-charts module, that we will try to release later today.
