### ISSUE TITLE
i followed the kendo-angular-grid and downloaded from package.json version 0.5.3

### ISSUE THREAD

**Issue by MKPMani** [telerik/kendo-angular2#63]
after installed this control it includes two controls kendo-charts and kendo-drawing. after put on wwwroot folder run by gulp. when i ran the application throw error : chroma-js not loading. i tried install chroma-js also still same error, cant load

**Comment by petyosi** [comment]
I am afraid that there is not much that we can do to help. Since you mention gulp, you are using a setup quite different from the common ones. You may seek assistance in StackOverflow.
