### ISSUE TITLE
dynamically load kendo-tabstrip-tab

### ISSUE THREAD

**Issue by sanket360** [telerik/kendo-angular2#64]
My simple kendo-tabstrip component looks like this-
```
<kendo-tabstrip (select)="onTabSelected($event)">
   <kendo-tabstrip-tab [title]="'tab1'" [selected]="true">
        Kendo UI - Tab Strip Demo
   </kendo-tabstrip-tab>
   ....
   ....
```
How to do I load component dynamically in kendo-tabstrip-tab?

**Comment by KirilNN** [comment]
Hi @sanket360,

Can you please elaborate a bit more on "dynamically loaded" component?

**Comment by petyosi** [comment]
I think that this SO question is about the same: http://stackoverflow.com/questions/40195864/how-can-we-load-component-dynamically-in-kendo-tabstrip-tab

**Comment by sanket360** [comment]
@KirilNN 
If I pass array of object to kendo-tabstrip then it should load that many kendo-tabstrip-tab.

For example, 
if array of object has 3 items then it should show 3 tabs.
if array has 5 items then it should show 5 tabs and so on...

I am not looking to hard code kendo-tabstrip-tab in my html template.

**Comment by KirilNN** [comment]
@sanket360 what about [this](http://plnkr.co/edit/rxOnRbYYghcmbWfrQu0u?p=preview)

**Comment by sanket360** [comment]
@KirilNN yes similar to this. but wanted to load entire component in each tab.

**Comment by KirilNN** [comment]
I can not see a problem doing it with an entire component. In case you have spotted a bug please for the plunkr provided in my previous response and edit it in order to show the problematic behavior - then I will be happy to investigate further.

I will close the issue for now

**Comment by sanket360** [comment]
@KirilNN could you please take a look at this plunker - http://plnkr.co/edit/nPzIDHrlgVGkH783dVWx?p=preview

**Comment by KirilNN** [comment]
Please try with the latest version as shown here:

http://plnkr.co/edit/8oAlXLN4aW91cw9wDisW?p=preview
