### ISSUE TITLE
Kendo-Searchbar not affected when disabling ComboBox

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular2#66]
Plunker: 
http://plnkr.co/edit/Tl6puiuFZzyO7DMvbvhR?p=preview 

Is there a way to disable the searchbar?

**Comment by tapopov** [comment]
Hey @simon11196 

Thanks for reporting this. The issue is now fix in version 0.14.2

**Comment by simon11196** [comment]
Great, thanks  :)
