### ISSUE TITLE
Combobox placeholder

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular2#69]
Is there a way to use the placeholder attribute in the Combobox-searchbar?

**Comment by ggkrustev** [comment]
@simon11196 currently not, but the functionality will be added soon (it is in development). We will update the thread once it is released.

**Comment by simon11196** [comment]
Great, thanks :+1:

**Comment by tapopov** [comment]
Hi @simon11196,
The ComboBoxComponent supports the [placeholder] attribute with version 0.15.0.
