### ISSUE TITLE
Add CategoryAxis to SeriesItemComponent

### ISSUE THREAD

**Issue by Cabeda** [telerik/kendo-angular2#71]
I need to create multiple panes with a category axis for each. In your documentation for the CategoryAxisItemComponent the name attribute references this feature even though it isn't enabled.

**Comment by tsvetomir** [comment]
I've managed to reproduce the issue in [this plunkr](http://plnkr.co/edit/96ki9MwDxEb1RcUqpVoT?p=preview). Will investigate and update this issue when we have a fix.

**Comment by tsvetomir** [comment]
Fixed in @progress/kendo-angular-charts@0.7.5
