### ISSUE TITLE
I have installed the Grid Component but my module is not recognising it

### ISSUE THREAD

**Issue by ThinkAboutGitHub** [telerik/kendo-angular2#72]
I have installed the Grid Component via npm install --save @progress/kendo-angular-grid, this appeared to complete successfully.  The version that was installed was 0.50.

I am using VS 2015 to run my angular 2 solution.  I got the buttons working fine, but my module is not recognising the grid.

At the top of my app.module.ts I have this: 

import { GridModule } from '@progress/kendo-angular-grid'

but when I add 'GridModule' to the imports array, it is highlight Red and saying it can't find it.

In my packages I have this:
packages: {
      '@progress/kendo-angular-buttons': {
          main: "./dist/npm/js/main.js",
          defaultExtension: "js"
      },
      '@progress/kendo-angular-grid': {
          main: "./dist/npm/js/main.js",
          defaultExtension: "js"

I can't figure out why its not picking up the GridModule?  It is telling me that it cannot be properly resolved.  And that it is possibly located in an inaccessible module.
![capture](https://cloud.githubusercontent.com/assets/18153399/19843432/0fc7e656-9f6e-11e6-9dbe-d8ed8bedd2fa.PNG)

Editing to add, I just tried out the DropDownModule and I appear to have the same issue.  The only module I have been able to get working is the ButtonModule

**Comment by rusev** [comment]
We are not aware of such issue.

A quick search in stackoverflow shows that this might be issue with **_Resharper_**. See the following threads:
 - http://stackoverflow.com/questions/34036739/angular-2-visual-studio-2015-update-1-type-script-configuration
 - http://stackoverflow.com/questions/34592390/visual-studio-2015-update-1-enterprise-with-resharper-10-ultimate-cannot-be
 - http://stackoverflow.com/questions/28098372/why-was-the-global-angular-variable-removed-from-angularjs-typescript-definite

**Comment by ThinkAboutGitHub** [comment]
Thanks for the links. i have disabled ReSharper to take that out of the equation, but unfortunately my Grid still does not load.

I can just seeing the 'loading...' message and when i look at Chrome dev tools it just says

"localhost/:20 Error: SyntaxError: Unexpected token <"

**Comment by rusev** [comment]
We will need a reproduction of the problem in order to assist. Can you provide one?
