### ISSUE TITLE
onClose event on kendo dialog.

### ISSUE THREAD

**Issue by Hrish44** [telerik/kendo-angular2#74]
I used the exact same example for the kendo dialog events. The onAccept and onDecline seems to be working fine but the onClose event does not seem to be fired. I also tried it on the same plunker provided and it does not work there too. Is this a known issue and would be fixed or is it already fixed? Just for the reference, I am also providing the example plunker below.

[http://plnkr.co/edit/futOgrFxP76mfjEHpWga?p=preview](url)

**Comment by gyoshev** [comment]
@Hrish44 thanks for reporting this. Version 0.12 of the dialog renames the `onClose` event to `close`, for consistency with other components. The documentation will be updated with the next upload. Here is a [functional plunkr](http://plnkr.co/edit/qBFgvBoYm6DfxnrEZu9D?p=preview).

**Comment by Hrish44** [comment]
It seems to be working now. Thanks a lot.
