### ISSUE TITLE
Going through form controls stuck focus at <kendo-dropdownlist>

### ISSUE THREAD

**Issue by ilianiv** [telerik/kendo-angular2#77]
Cannot move form control focus forward or back (with Tab or Shift+Tab) when I reach <kendo-dropdownlist> component.

PS: Setting `tabIndex` won't help

### Plunker
http://plnkr.co/edit/Ecm66l?p=preview

**Comment by tapopov** [comment]
It seems that the DropDownList was stealing the <TAB> keyboard event and preventing its default behavior. This has been fixed in v0.16.13
Thanks for reporting this, @ilianiv
