### ISSUE TITLE
File select dialog does not open within Chrome

### ISSUE THREAD

**Issue by MarcHaid** [telerik/kendo-angular2#78]
Hi,

I added the Upload component to our app and the file selection dialog does not open. I am using Chrome version Version 54.0.2840.71 m (64-bit). I tried to reproduce the behaviour here at Plunkr:

http://plnkr.co/edit/hopuyNK5QEHx4Hfc1wyG?p=preview

Here the dialog opens. Might it be a side effect with the Grid component? I found no possibility to add this component to the plunkr.

If I open our app with the IE 11 everything works fine.

Are there anything missing to make it running?

Thanx for your feedback.

Kind regrads,

Marc

**Comment by tsvetomir** [comment]
I'm afraid we can't help without reproducing the issue first.

Perhaps you can try removing components, styles, etc. to see if that helps.

**Comment by tsvetomir** [comment]
@Raisolution can you confirm these issue? If not, I think we should close this until we have a repro.

**Comment by Raisolution** [comment]
Haven't met the problem on our end. We will inspect the repro, if provided.

**Comment by MarcHaid** [comment]
We tried to reproducing the problem, but it seems that other components of our solution produce this problem. We can not publish the other components on plunkr. Sorry.
