### ISSUE TITLE
ComboBox - 0 (zero) is not valid primitive type 

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular2#81]
Using combo box you can not have 0 as value (we have 1 for positive value and 0 for negative).

```
VM5378 core.umd.js:3468 Error: Expected initial value of primitive type. See http://www.telerik.com/kendo-angular-ui/components/dropdowns/combobox/#value-selection
```

### Plunker (check out the console):
http://plnkr.co/edit/R2M2Lwg9v59UCUV4MN3y?p=preview

**Comment by valchev** [comment]
It seems that the value is displayed but the corresponding item is not selected in the list.

Example: http://plnkr.co/edit/05d359ZZ7Cz514F0sVba?p=preview
