### ISSUE TITLE
Grid is not updating when data changes

### ISSUE THREAD

**Issue by HGitTest** [telerik/kendo-angular2#82]
In the following plunker : http://plnkr.co/edit/cVFD5UNqu59XuzjCiCT3

when you click the "update values" button, you can see the checkboxes are correctly updated, but not the values. (UnitPrice should be doubled on each click)

Am i missing something here ?
Is there a way to force the grid to refresh ?

**Comment by rusev** [comment]
Indeed I can confirm that there is an issue with this scenario. We are working on resolving it.

I'll update this thread once we have more details.

**Comment by rusev** [comment]
@HGitTest a new package version was released containing a fix for this issue.

The original example should properly work now.
