### ISSUE TITLE
Sum each PanesComponent's height to set chart's height

### ISSUE THREAD

**Issue by Cabeda** [telerik/kendo-angular2#83]
When generating a chart I have to set multiple panes dynamically and as such I don't know the height the chart will have. I'm trying to set the height through the PaneComponent but the current version sets k.chart class with `height: auto ` and hides all but the first pane.

The alternative is to set chart area height and the pane height.

Could it be a future feature?

**Comment by tsvetomir** [comment]
You should be able to set the chart height using a style binding, provided that you know the total height of the panes:
```
@Component({
    selector: 'my-app',
    template: `
        <kendo-chart [style.height]="totalHeight()">
...
        </kendo-chart>
    `
})
export class AppComponent {
    private totalHeight() {
      return '620px'; // panes height + chart area margins
    }
}
```

See [this plunkr](http://plnkr.co/edit/PT9gohrFOKKbMs0zcUfj?p=preview) for a demo.

**Comment by Cabeda** [comment]
Thanks for the time :-)
