### ISSUE TITLE
PanelBar header does not support templates for its item rendering

### ISSUE THREAD

**Issue by raghuSanapathi** [telerik/kendo-angular2#85]
Hi,
I'm not able to render material font icons in Panel Bar. Can any one help me how to achieve this so that i can show material font icon along with text in Panel Bar header?

**Comment by raghuSanapathi** [comment]
Can i get any answer for this?

**Comment by tsvetomir** [comment]
This feature is on our short-term plans and should be available within 2 weeks or so.

**Comment by KirilNN** [comment]
@ivanchev It was again requested by a user on SO. Maybe we can prioritize it?  It is already supported by the TabStrip.

**Comment by maniac1979** [comment]
Hi, any news on this?

**Comment by vladimirivanoviliev** [comment]
Hi @maniac1979,
the feature is now ready on our side and you can expect it to be available as updated `Layout` package in the following days.
