### ISSUE TITLE
Define exportAs for all public components/directives

### ISSUE THREAD

**Issue by rusev** [telerik/kendo-angular2#86]
Currently there is no easy way of getting component/directive reference in the template. This can be achieved if we  define `exportAs` for all of our public components/directives. 

A possible convention for this could be as follows: `kendo${ComponentName}`.

Example: 
```
@Component({
  selector: 'kendo-grid',
  exportAs: 'kendoGrid'
})
```

In the consuming component Grid reference will be obtained as follows:
```
@Component({
  template: `
   <kendo-grid #myGridInstance="kendoGrid">
   </kendo-grid>
  `
})
```

What do you think?

**Comment by tsvetomir** [comment]
The rule is to "camelize" the kebab-cased selector for all widgets, right?

**Comment by rusev** [comment]
Yes. It seems like a "convention" on angular side.

For reference [NgForm](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/ng_form.ts#L65) and [NgModel](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/ng_model.ts#L110).

**Comment by tsvetomir** [comment]
@rusev did I miss any package?

**Comment by rusev** [comment]
Only a few more: popup, charts, layout, sortable, scrollview. :)

**Comment by tsvetomir** [comment]
I misunderstood this was only usable for forms, for no apparent reason :)
