### ISSUE TITLE
Bootstrap theme is not working correctly

### ISSUE THREAD

**Issue by dzmitrypaulouski** [telerik/kendo-angular2#87]
I am installed bootstrap theme using npm (current package version is 0.10.0).

So I've added it to my project:
```
@import '~bootstrap/scss/bootstrap';
@import '~@telerik/kendo-theme-bootstrap/dist/all';
```

In this case some components looks strange. For example upload control doesn't have icons in selected files:
![image](https://cloud.githubusercontent.com/assets/10211927/20302302/c1a9e9b2-ab37-11e6-8b04-6c7e8347a765.png)

Also I've tried to add SASS sources to project:
`@import '~@telerik/kendo-theme-bootstrap/src/packages/all';`
But I had such error:
![image](https://cloud.githubusercontent.com/assets/10211927/20302609/fb58bf2a-ab38-11e6-9166-e0f7decd79d8.png)

I've checked sources and found that there are many incorrect references like `@import "../../node_modules/bootstrap/scss/variables";` (file is located in /node_modules/@telerik/kendo-theme-bootstrap/src/packages)

**Comment by tsvetomir** [comment]
The Bootstrap theme is still in active development and we do not recommend using it for the moment.

Expect updates in the next few months.
