### ISSUE TITLE
Binding to Grid - cannot iterate data

### ISSUE THREAD

**Issue by Catchops** [telerik/kendo-angular2#88]
Since this is not in official release yet, I'm not sure if this is a bug, or if it is something in my code.  I have used the [Data Binding](http://www.telerik.com/kendo-angular-ui/components/grid/data-binding/) Example and applied it to my own application.  

The problem I am seeing is that upon the actual return of data - while the data is being mapped to the GridDataResult I get the following error message:

> EXCEPTION: Error in ./TableBodyComponent class TableBodyComponent - inline template:2:8 caused by: this.data[iterator_1.$$iterator] is not a function

Here is the "fetch" function - which is almost exactly the same as the code examples including a fix with the "inlinecount":

    private fetch(tableName: string, state: any): Observable<GridDataResult> {
        debugger;
        const queryStr = `${toODataString(state)}&$inlinecount=allpages`;
        return this.http.get(`${this.BASE_URL}${tableName}?${queryStr}`)
            .map(response => response.json())
            .map(response => (<GridDataResult>{
                data: response.value,
                total: parseInt(response["@odata.count"], 10)
            }));
    }

(note, you can see the debugger statement in there where I stop the code)

The call is to an oData service.  Here is the returned JSON:

> [{"$id":"1","Organization":null,"Party":null,"Party1":null,"HospitalId":35947,"IsPending":false,"Beds":null,"OccupancyPercent":null,"OutpatientVisits":null,"Admissions":null,"Births":null,"ERVisits":null,"InpatientSurgeries":null,"OutpatientSurgeries":null,"Personnel":null,"HasTraumaCenter":false,"DOsOnStaff":null,"MDsOnStaff":null,"CreatedByPartyId":2,"CreatedDate":"2016-10-18T10:55:56.56","UpdatedByPartyId":null,"UpdatedDate":null},{"$id":"2","Organization":null,"Party":null,"Party1":null,"HospitalId":35948,"IsPending":false,"Beds":null,"OccupancyPercent":null,"OutpatientVisits":null,"Admissions":null,"Births":null,"ERVisits":null,"InpatientSurgeries":null,"OutpatientSurgeries":null,"Personnel":null,"HasTraumaCenter":false,"DOsOnStaff":null,"MDsOnStaff":null,"CreatedByPartyId":2,"CreatedDate":"2016-10-18T10:55:56.56","UpdatedByPartyId":null,"UpdatedDate":null},{"$id":"3","Organization":null,"Party":null,"Party1":null,"HospitalId":35949,"IsPending":false,"Beds":null,"OccupancyPercent":null,"OutpatientVisits":null,"Admissions":null,"Births":null,"ERVisits":null,"InpatientSurgeries":null,"OutpatientSurgeries":null,"Personnel":null,"HasTraumaCenter":false,"DOsOnStaff":null,"MDsOnStaff":null,"CreatedByPartyId":2,"CreatedDate":"2016-10-18T10:55:56.56","UpdatedByPartyId":null,"UpdatedDate":null},{"$id":"4","Organization":null,"Party":null,"Party1":null,"HospitalId":35950,"IsPending":false,"Beds":null,"OccupancyPercent":null,"OutpatientVisits":null,"Admissions":null,"Births":null,"ERVisits":null,"InpatientSurgeries":null,"OutpatientSurgeries":null,"Personnel":null,"HasTraumaCenter":false,"DOsOnStaff":null,"MDsOnStaff":null,"CreatedByPartyId":2,"CreatedDate":"2016-10-18T10:55:56.56","UpdatedByPartyId":null,"UpdatedDate":null},{"$id":"5","Organization":null,"Party":null,"Party1":null,"HospitalId":35951,"IsPending":false,"Beds":null,"OccupancyPercent":null,"OutpatientVisits":null,"Admissions":null,"Births":null,"ERVisits":null,"InpatientSurgeries":null,"OutpatientSurgeries":null,"Personnel":null,"HasTraumaCenter":false,"DOsOnStaff":null,"MDsOnStaff":null,"CreatedByPartyId":2,"CreatedDate":"2016-10-18T10:55:56.56","UpdatedByPartyId":null,"UpdatedDate":null}]

Any thoughts are appreciated.

Thanks!

**Comment by rkonstantinov** [comment]
Judging from the error I suppose the supplied value for the `GridDataResult`'s data field is not iteratable for example it is undefined. From the note you have made about the `inlinecount` I guess you are using OData v2/v3, where the original sample is using v4. You should check that the server response is correctly mapped to the `GridDataResult`. (OData v4 and v2 have different server response formats and you will need to use different response field names)
