### ISSUE TITLE
Optimize UploadComponent

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular2#89]
The `UploadComponent` is listening to `document:dragover` and is causing way too many unnecessary change detection passes. On medium to large applications, this causes a lot of lag when performing drag and drop anywhere else. This event doesn't require the model to be checked, so it should be running outside the NgZone for a lot better performances.

    this.ngZone.runOutsideAngular(() => document.addEventListener('dragover', this.documentDragListener));

I have to comment out the plugin on my side for the time being.

**Comment by tsvetomir** [comment]
Thanks for the heads-up! We're using `runOutsideAngular` in a few other places, but so far not in the Upload.

/cc @rusev

**Comment by rusev** [comment]
Indeed we should utilize this pattern where possible. Subscribing for document events is a good place to start.
