### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by underlog** [telerik/kendo-angular2#9]
A basic abstraction, we need it for the #3 (dropdowns) package.

**Comment by tsvetomir** [comment]
That's also needed for implementing a Tooltip

**Comment by ggkrustev** [comment]
After an offline discussion with @tsvetomir, we come up with the following Popup spec:

https://gist.github.com/ggkrustev/3692397b76942a954f86211a45e9e79d

Comment in the Gist or here if you would like to add/update/remove smth form the spec.

**Comment by ggkrustev** [comment]
# Popup Component
This would be an Angular2 component that shows/hides a specific content. The `popup` could be attached to specific 'anchor' element.

The component will be a building block of [`DropDowns`](https://github.com/telerik/kendo-angular2/issues/3), `Date/Time pickers` and [`Chart Tooltip`](https://github.com/telerik/kendo-angular2/issues/2).

## Design goals
- Render any content/template/component
- Keep the Popup position in the App tree
- Position component using absolute [x,y] or an anchor element
- Support a boundary detection
- Configure the view port (used for boundary detection)
- Animated show/hide

## Features
Planned features for the Beta release include:
- render a custom template content with the support of `<ng-content>`
- animated show/hide
- Position next to an anchor using [a specific position strategy](https://gist.github.com/ggkrustev/1406b5fbe348fba9649f6d45ab8bdb92)
- Boundary detection support with [a specific collision strategy](https://gist.github.com/ggkrustev/163c1ccfce3c77573c78f7a272f12407)

The following features are unlikely to ship for the Beta release, but will follow in later releases:
- configure the view-port element

### API
- open(): void //opens the popup
- close(): void //closes the popup
- toggle(): void //toggles the popup visibility
- position(x?:number, y?:number): void //repositions the popup to specific [x,y]
- isVisible(): boolean //returns the visibility state of the popup
- connectTo(anchor: ElementRef) //connects the popup to specific anchor

### Events
- open
- close

## Sample Usage

The below example demonstrates how to open/close popup on button click:
```
import 'core-js/es6';
import 'core-js/es7/reflect';
import 'zone.js/dist/zone';

import { Component, ElementRef, ViewChild } from '@angular/core';
import { bootstrap } from '@angular/platform-browser-dynamic';
import { POPUP_DIRECTIVES } from '../src/main';

@Component({
  directives: [PopupComponent],
  selector: 'kendo-my-app',
  template: `
  <button #anchor (click)="onToggle(popup)">{{toggleText}}</button>
  <kendo-popup #popup="kendo-popup" [anchor]="anchor">
    <ul class="content-ul">
        <li>Item1</li>
        <li>Item2</li>
        <li>Item3</li>
    </ul>
  </kendo-popup>
  `
})
class AppComponent {
    @ViewChild('anchor') anchor: ElementRef;
    private toggleText: string = "Show";

    public onToggle(popup: PopupComponent): void {
        popup.toggle();

        this.toggleText = popup.isVisible() ? "Hide" : "Show";
    }
}

bootstrap(AppComponent);
```

## Supported browsers
Target is IE9+ and all modern browsers.

## Accessibility
Basic a11y support will be provided, although the main control over the content rendering is in the developer's hands

**Comment by tsvetomir** [comment]
Do you think it's a good idea to use `*ngIf` in place of `open`, `close`, `isOpen`, `toggle`?

If it's in the component tree, it's _open and visible_. If you remove it, it's _closed and hidden_.

**Comment by ggkrustev** [comment]
Yeah, I totally agree. I will expose `visible` as property binding. Thus the need of four methods will be eliminated :).

I will update the spec shortly.

P.S. The popup also uses *ngIf, as this is the "general best practice" when it comes to showing/hiding elements.

**Comment by underlog** [comment]
Done - http://www.telerik.com/kendo-angular-ui/components/popup/
