### ISSUE TITLE
Charts not working if Kendo.all.min.js is included in the project

### ISSUE THREAD

**Issue by mustafasadikot** [telerik/kendo-angular2#90]
Hi Team,

I have an angular 2 application where I am using Kendo charts. In the same application I need to use Kendo Diagram and for that I have included kendo.all.min.js in the index.html.

But since then my charts are not working. I looked for the issue and narrowed it down to below piece of code:

```
ChartComponent.prototype.init = function () {
	        var element = this.element.nativeElement.querySelector('.k-chart-surface');
	        this.instance = new charts.Chart(element, this.options, this.theme);
	        this.bindEvents();
	    };
```

Here the element that is used for the creation of chart is null all the time and as a result throws below exception:

`TypeError: Cannot read property 'className' of null at addClass (add-class.js:75)`

Note: This works if I remove kendo.all.min.js from the project.

**Comment by tsvetomir** [comment]
I've tried reproducing this in [a plnkr](http://plnkr.co/edit/FrXv0PfD3M2r7ZYbpaSn?p=preview), but without success. Can you share a runnable example that we can debug with?

**Comment by mustafasadikot** [comment]
@tsvetomir Please find a demo project [here](https://github.com/hem19/kendo-angular2-demo/tree/master/DemoApp/DemoApp)

**Comment by tsvetomir** [comment]
Thanks for the sample project.

It appears that the `<kendo-chart>` element is being picked-up by our [Web Components](http://docs.telerik.com/kendo-ui/third-party/webcomponents) integration. Auch.

The way to get around this at the moment is to load [individual scripts](http://docs.telerik.com/kendo-ui/intro/installation/what-you-need#build-scripts). Just make sure that you don't include `kendo.webcomponents.js`. I've prepared [a sample fix](https://github.com/tsvetomir/kendo-angular2-demo/commit/72d75f369dcfeb07c6dc94e4ce05a43630052a34) in my fork.

As a long-term fix, we're excluding webcomponents from `kendo.all.min.js` in the next major release of Kendo UI for jQuery.

**Comment by mustafasadikot** [comment]
@tsvetomir Thanks for a quick response. The solution is working for now. Looking forward to a permanent fix.
