### ISSUE TITLE
DropdownList - Expression has changed after it was checked

### ISSUE THREAD

**Issue by moxival** [telerik/kendo-angular2#91]
If you try to open a dropdown list while there is still another dropdown opened you will get:

```javascript
EXCEPTION: Error in ./DropDownListComponent class DropDownListComponent - inline template:27:20 caused by: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.
```

This happens only when filterable is set to `true`

### Plunker
http://plnkr.co/edit/EJuk1ySwqNWKIyGuUKCf?p=preview

**Comment by dzmitrypaulouski** [comment]
I have the same issue. Do you plan to fix this issue or can you provide some workaround?

**Comment by valchev** [comment]
Hello guys,

@moxival thank you for bringing this to our attention.
@dzmitrypaulouski we will fix the problem in a short period of time, most probably next week.
