### ISSUE TITLE
Kendo Grid Column - *ngIf Error after switching to Webpack HTML Bundler (raw-loader)

### ISSUE THREAD

**Issue by simon11196** [telerik/kendo-angular2#92]
Hi,

today we changed our projekt to html bunding via Webpack (raw-loader). 

Now the following code, which already worked before, leads to the error at the end, as soon as "flag" get swichted to true:

`<kendo-grid [data]="[{ID: 1, Bez: 'test'}]" >
    <kendo-grid-column field="ID" title="ID" width="120" *ngIf="flag">
    </kendo-grid-column>
    <kendo-grid-column field="Bez" title="BezName">
    </kendo-grid-column>
    <kendo-grid-column width="230" >
    </kendo-grid-column>
</kendo-grid>`

'vendor.bundle.js:30943 TypeError: Cannot read property 'appendChild' of null
    at appendChild (vendor.bundle.js:46210)
    at View_ProjektAnlegenComponent1.visitRootNodesInternal (component.ngfactory.js:541)
    at View_ProjektAnlegenComponent1.AppView._renderAttach (vendor.bundle.js:32995)
    at View_ProjektAnlegenComponent1.AppView.attachAfter (vendor.bundle.js:32973)
    at ViewContainer.attachView (vendor.bundle.js:33321)
    at ViewContainerRef_.insert (vendor.bundle.js:33476)
    at ViewContainerRef_.createEmbeddedView (vendor.bundle.js:33456)
    at NgIf.set [as ngIf] (vendor.bundle.js:614)
    at Wrapper_NgIf.check_ngIf (wrapper.ngfactory.js:17)
    at CompiledTemplate.proxyViewClass.View_ProjektAnlegenComponent0.detectChangesInternal (component.ngfactory.js:373)'

Does anyone have an idea? Thanks for your replies!

**Comment by rusev** [comment]
We are not aware of such issue. Can you provide us sample project where it can be observed?

**Comment by HJoost** [comment]
It's a bit difficult because this is not possible to rearrange in plunker. Tomorow we try to build an project that we can upload.

**Comment by simon11196** [comment]
We finally found the problem. We used Angular version 2.2.0 when the error occured. With Angular 2.1.1 it works fine.

Sample project:
[Angular 2.2.0 + Webpack + Kendo.zip](https://github.com/telerik/kendo-angular2/files/596998/Angular.2.2.0.Webpack.Kendo.zip)

I used the [angular2-webpack-starter project,](https://github.com/AngularClass/angular2-webpack-starter) updated Angular to 2.2.0 and added kendo-grid to the home-component.

**Comment by rusev** [comment]
Thank you for the example. We will investigate further and report back.

**Comment by rusev** [comment]
Unfortunately we are able to determine what is the cause for the exception in your application. However I've just cloned [angular2-webpack-starter project](https://github.com/AngularClass/angular2-webpack-starter), updated it to Angular 2.2.0 and added the Grid module. All seems to be working properly. You ca find it attached bellow:

[angular2-webpack-starter.zip](https://github.com/telerik/kendo-angular2/files/597747/angular2-webpack-starter.zip)
