### ISSUE TITLE
Browser support: PanelBarItem not working on IE 9

### ISSUE THREAD

**Issue by saradalco** [telerik/kendo-angular2#94]
I am using the PanelBar component.  
When I run the app on IE 9 it shows a blank white screen and this error appears in the Console:

Error in ./PanelBarItemComponent class PanelBarItemComponent - inline template:2:12 caused by: Unable to get property 'add' of undefined or null reference

Angular version: 2.0.1
Typescript version: 2.03
 
Thanks.

**Comment by KirilNN** [comment]
Do you have the necessary polyfills installed for IE 9 as listed here:

https://angular.io/docs/ts/latest/guide/browser-support.html#!#classlist

**Comment by vladimirivanoviliev** [comment]
I will close the thread for now as it seems the issue was not related to the component.
