### ISSUE TITLE
kendo-angular2-inputs

### ISSUE THREAD

**Issue by haoguanjun** [telerik/kendo-angular2#95]
In kendo-angular2-inputs , it define a KendoDraggableDirective directive, but not export it.
it's a useful directive. Could you add it to exports list?

**Comment by KirilNN** [comment]
We can do that, but we will need to document it as well. @rusev what do you think?

**Comment by rusev** [comment]
This directive is intentionally private. It is for internal use only and might change in the future. Thus I suggest to leave it this way.

At some point we might introduce another package where all drag&drop featureс live officially.

**Comment by haoguanjun** [comment]
thanks. waiting this package.
