### ISSUE TITLE
Tabstrip - Static content between tab title and tab content

### ISSUE THREAD

**Issue by maximedupre** [telerik/kendo-angular2#97]
I'm currently stuck at `v12.1` of the Layout module, because there are some breaking changes after that that doesn't allow me to add elements between the tab titles and the tab content.

    <kendo-tabstrip>
        <div>
            Static stuff that will be displayed for every tab, between the tab title and content.
        </div>

        <kendo-tabstrip-tab> 
            ...
        </kendo-tabstrip-tab>
        <kendo-tabstrip-tab> 
            ...
        </kendo-tabstrip-tab>
    </kend-tabstrip>

This is working in `v12.1`, but not after that. In the newest version, the "static elements" are ignore/removed from the HTML.

**Comment by rusev** [comment]
This behavior is a side effect from using `ng-content` for rendering of tab content. However it was never intended to support such rendering.

**Comment by maximedupre** [comment]
So nothing has been though for shared content between all tabs?

**Comment by rusev** [comment]
No, it has never been a requirement for this component.

**Comment by tsvetomir** [comment]
Sharing content between all tabs sounds like a custom component to me.

**Comment by maximedupre** [comment]
@tsvetomir I guess it's the best option if you have no plans to support this feature. It would still be best to not have to repeat the markup for each tab. Maybe for a future release!

**Comment by maximedupre** [comment]
You could also want to have only one instance of the component since it's shared, instead of one instance per tab

**Comment by tsvetomir** [comment]
That's a valid argument for having a dedicated shared content placeholder.
Please, cast your vote for this feature on <a href="http://kendoui-feedback.telerik.com/forums/555517-kendo-ui-for-angular-2-feedback">our UserVoice feedback portal  &nearr;</a> if you have a minute.
