### ISSUE TITLE
Grid - PageChangeEvent.take is string instead of number

### ISSUE THREAD

**Issue by P-H-F** [telerik/kendo-angular2#99]
The grid shows more items than specified in the page-size option.
Using kendo-angular-grid@0.6.2.

**Plunker:**
http://plnkr.co/edit/0cUUaJXFHLT7R90HS1XR?p=preview

**Steps to reproduce it**

1. Change the page-size from to e.g.: 10.
2. Switch to another page. e.g.: 2.

Now the grid shows the items 10 - 99.

I've identified the cause of this due to the value `PageChangeEvent.take` being a `string`.
This causes the calculation `this.skip + this.pageSize` in the `loadProducts` method to return `1010` instead of `20`.

**Workaround:**
Convert `PageChangeEvent.take` to a number when assigning it to the local variable.

**Comment by KirilNN** [comment]
@P-H-F - thanks for reporting it. Version `0.6.3` where the issue is fixed is now live. 

Please test it out and let me know if the problem persists!

**Comment by P-H-F** [comment]
@KirilNN - works like a charm. Thanks for the prompt response/fix.
